import { LandingStyle, StyleBrand, StyleTokens, TypographyVariant, ColorPalette } from './types';

const corporateBaseTokens: StyleTokens = {
  componentRadius: '4px',
  componentBorder: '1px solid rgba(15,23,42,0.12)',
  componentShadow: 'none',
  componentBg: '#FFFFFF',
  sectionPadding: '88px',
  contentGap: '20px',
  transitionDuration: '150ms',
  themeMode: 'light',
  extraTokens: {
    buttonStyle: 'filled',
    buttonRadius: '4px',
    ctaShadow: 'none',
    sectionBgAlternate: '#F8FAFC',
    containerMaxWidth: '1180px',
    headingWeight: '600',
    headingLetterSpacing: '0em',
    gradientOverlay: 'none',
    overlayOpacity: '1',
    navbarHeight: '64px',
    countdownStyle: 'normal',
  },
};

const corporateTypography: TypographyVariant[] = [
  { name: 'Corporativo', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Inter', bodyFont: 'Inter' },
  { name: 'Ejecutivo', headingScale: 1.2, bodyScale: 1.0, headingFont: 'Public Sans', bodyFont: 'Inter' },
  { name: 'Clásico', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Libre Baskerville', bodyFont: 'Source Sans 3' },
  { name: 'Institucional', headingScale: 1.1, bodyScale: 1.0, headingFont: 'Source Sans 3', bodyFont: 'Source Sans 3' },
  { name: 'Gerencial', headingScale: 1.15, bodyScale: 1.0, headingFont: 'IBM Plex Sans', bodyFont: 'IBM Plex Sans' },
  { name: 'Notarial', headingScale: 1.2, bodyScale: 1.05, headingFont: 'Spectral', bodyFont: 'Inter' },
  { name: 'Directivo', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Lato', bodyFont: 'Open Sans' },
  { name: 'Sobrio', headingScale: 1.1, bodyScale: 1.0, headingFont: 'Hanken Grotesk', bodyFont: 'Inter' },
];

const corporateColorProposals: ColorPalette[] = [
  { name: 'Azul Corporativo', primary: '#1E3A8A', secondary: '#F8FAFC', accent: '#0EA5E9' },
  { name: 'Verde Institucional', primary: '#14532D', secondary: '#F0FDF4', accent: '#22C55E' },
  { name: 'Rojo Sobrio', primary: '#7F1D1D', secondary: '#FEF2F2', accent: '#EF4444' },
  { name: 'Azul Petróleo', primary: '#164E63', secondary: '#ECFEFF', accent: '#06B6D4' },
  { name: 'Púrpura Serio', primary: '#3B0764', secondary: '#FAF5FF', accent: '#A855F7' },
  { name: 'Grafito Business', primary: '#111827', secondary: '#F9FAFB', accent: '#F59E0B' },
  { name: 'Cian Dócil', primary: '#0C4A6E', secondary: '#F0F9FF', accent: '#0EA5E9' },
  { name: 'Esmeralda Formal', primary: '#064E3B', secondary: '#ECFDF5', accent: '#10B981' },
];

const corporateBrands: StyleBrand[] = [
  {
    name: 'Junta Directiva',
    description: 'Azul corporativo sobrio: instituciones y programas oficiales.',
    tokens: {
      componentRadius: '4px',
      componentBorder: '1px solid rgba(30,58,138,0.2)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '20px',
      transitionDuration: '150ms',
      themeMode: 'light',
    },
    typography: { name: 'Corporativo', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Inter', bodyFont: 'Inter' },
    palette: { name: 'Azul Corporativo', primary: '#1E3A8A', secondary: '#F8FAFC', accent: '#0EA5E9' },
  },
  {
    name: 'Área de Finanzas',
    description: 'Verde institucional: resultados, métricas y confianza.',
    tokens: {
      componentRadius: '4px',
      componentBorder: '1px solid rgba(20,83,45,0.2)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '20px',
      transitionDuration: '150ms',
      themeMode: 'light',
    },
    typography: { name: 'Ejecutivo', headingScale: 1.2, bodyScale: 1.0, headingFont: 'Public Sans', bodyFont: 'Inter' },
    palette: { name: 'Verde Institucional', primary: '#14532D', secondary: '#F0FDF4', accent: '#22C55E' },
  },
  {
    name: 'Comité Legal',
    description: 'Rojo sobrio y tipografía serif: certificaciones y compliance.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(127,29,29,0.2)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '20px',
      transitionDuration: '150ms',
      themeMode: 'light',
    },
    typography: { name: 'Notarial', headingScale: 1.2, bodyScale: 1.05, headingFont: 'Spectral', bodyFont: 'Inter' },
    palette: { name: 'Rojo Sobrio', primary: '#7F1D1D', secondary: '#FEF2F2', accent: '#EF4444' },
  },
  {
    name: 'Operaciones',
    description: 'Azul petróleo: procesos, eficiencia y expansión.',
    tokens: {
      componentRadius: '4px',
      componentBorder: '1px solid rgba(22,78,99,0.2)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '20px',
      transitionDuration: '150ms',
      themeMode: 'light',
    },
    typography: { name: 'Institucional', headingScale: 1.1, bodyScale: 1.0, headingFont: 'Source Sans 3', bodyFont: 'Source Sans 3' },
    palette: { name: 'Azul Petróleo', primary: '#164E63', secondary: '#ECFEFF', accent: '#06B6D4' },
  },
  {
    name: 'Tecnología',
    description: 'Grafito y ámbar: transformación digital empresarial.',
    tokens: {
      componentRadius: '6px',
      componentBorder: '1px solid rgba(17,24,39,0.15)',
      componentShadow: '0 1px 2px rgba(17,24,39,0.05)',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '20px',
      transitionDuration: '180ms',
      themeMode: 'light',
    },
    typography: { name: 'Gerencial', headingScale: 1.15, bodyScale: 1.0, headingFont: 'IBM Plex Sans', bodyFont: 'IBM Plex Sans' },
    palette: { name: 'Grafito Business', primary: '#111827', secondary: '#F9FAFB', accent: '#F59E0B' },
  },
  {
    name: 'Consultoría',
    description: 'Púrpura serio: estrategia, especialización y prestigio.',
    tokens: {
      componentRadius: '4px',
      componentBorder: '1px solid rgba(59,7,100,0.2)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '20px',
      transitionDuration: '150ms',
      themeMode: 'light',
    },
    typography: { name: 'Directivo', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Lato', bodyFont: 'Open Sans' },
    palette: { name: 'Púrpura Serio', primary: '#3B0764', secondary: '#FAF5FF', accent: '#A855F7' },
  },
];

export const corporateStyle: LandingStyle = {
  id: 'corporate',
  name: 'Corporate',
  description: 'Sobrio e institucional: autoridad formal, sin decoración, máxima claridad.',
  thumbnail: '/styles/corporate-thumb.svg',
  group: 'corporate',
  allowedSubscriptions: ['free', 'pro', 'premium'],
  layout: 'grid',
  tokens: corporateBaseTokens,
  typography: corporateTypography,
  brands: corporateBrands,
  availableSections: [
    {
      id: 'heroVideo',
      name: 'Portada Institucional',
      description: 'Redacta un titular institucional y directo: el resultado profesional que entrega el programa y a quién está dirigido. Tono formal y de confianza. CTA sobrio.',
      blueprint: 'Layout de ancho completo centrado: H1 sobrio en color primario, subhead de 1-2 líneas, CTA rectangular (radius 4px, sin sombra). Opcional banda de video/imagen alineada. Fondo claro, sin elementos decorativos.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'narrativeSections',
      name: 'Argumentación',
      description: 'Escribe de forma sobria y basada en evidencia: el problema profesional, la solución estructurada y por qué esta institución es la adecuada. Viñetas cortas y concretas.',
      blueprint: 'Bloques de texto estrechos y centrados. Títulos en primario, párrafos en gris medio. Sin imágenes, solo jerarquía tipográfica y separadores finos.',
      required: true, isRepeatable: true, contentType: 'text',
    },
    {
      id: 'benefits',
      name: 'Beneficios',
      description: 'Enumera beneficios concretos y verificables del programa (acreditaciones, salida laboral, red de contactos). Sin exageraciones.',
      blueprint: 'Grilla de 3 columnas con tarjetas blancas, borde fino de 1px y radius de 4px. Ícono pequeño arriba, título en bold, 2-3 líneas de texto.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'syllabus',
      name: 'Plan de Estudios',
      description: 'Describe el plan de estudios como un recorrido formal: etapas, certificaciones y habilidades concretas por módulo.',
      blueprint: 'Lista de acordeones o filas con separadores finos. Título en bold, detalle colapsable, sin cajas cerradas.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'mentorProfile',
      name: 'Equipo Docente',
      description: 'Presenta la trayectoria del docente con credibilidad: formación, experiencia, logros verificables. Tono institucional.',
      blueprint: 'Split: foto profesional a un lado, bloque de biografía formal al otro, insignias de trayectoria. Fondo secundario claro.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'testimonials',
      name: 'Referencias',
      description: 'Redacta 3-6 testimonios profesionales con resultado concreto y nombre completo/rol. Credibilidad y prueba verificable.',
      blueprint: 'Grilla de tarjetas blancas con borde fino. Cita en comillas, nombre y rol abajo en pequeño. Sin fotos llamativas.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'bonuses',
      name: 'Materiales Incluidos',
      description: 'Describe los materiales que incluye el programa (certificados, plantillas, licencias) con valor profesional.',
      blueprint: 'Tarjetas apiladas con recurso a la izquierda y descripción a la derecha. Sin excesos visuales, borde fino.',
      required: false, isRepeatable: true, contentType: 'mixed',
    },
    {
      id: 'guarantee',
      name: 'Garantía',
      description: 'Redacta la garantía en tono formal y contundente: plazo explícito y compromiso de devolución total.',
      blueprint: 'Bloque tipo certificado: borde fino resaltado, ícono de sello arriba, texto formal centrado. Sensación de seguridad.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'faqs',
      name: 'Preguntas Frecuentes',
      description: 'Responde objeciones institucionales: costos, modalidad, certificación, tiempo. Respuestas formales y directas.',
      blueprint: 'Acordeones de texto puro con separadores finos. Pregunta en bold, respuesta colapsable.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'countdownTimer',
      name: 'Cupos Limitados',
      description: 'Genera urgencia formal: fechas de inscripción y cupos por cohorte. Sin falsa escasez.',
      blueprint: 'Barra sobria con fondo accent: texto a la izquierda, reloj de dígitos a la derecha. Sin excesos.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'footer',
      name: 'Pie de Página',
      description: 'Disclaimer institucional, copyright y datos de contacto formal.',
      blueprint: 'Texto centrado small y sobrio, aviso legal en 1 línea.',
      required: false, isRepeatable: false, contentType: 'text',
    },
  ],
  defaultVisibility: {
    heroVideo: true,
    narrativeSections: true,
    benefits: true,
    syllabus: true,
    mentorProfile: true,
    testimonials: false,
    bonuses: false,
    guarantee: true,
    faqs: false,
    countdownTimer: false,
    footer: true,
  },
  colorProposals: corporateColorProposals,
  aiDirectives: 'Eres un redactor institucional. Tono formal, sobrio y basado en evidencia: sin superlativos vacíos, con datos y credenciales verificables. Cada promesa debe poder sostenerse con un dato o una acreditación.',
  aiWriterPersona: 'Copywriter corporativo. Escribe con claridad y autoridad, sin ruido ni decoración. Frases directas, tono profesional que transmite confianza institucional.',
};
