import { LandingStyle, StyleBrand, StyleTokens, TypographyVariant, ColorPalette } from './types';

const editorialBaseTokens: StyleTokens = {
  componentRadius: '0px',
  componentBorder: '1px solid rgba(41,36,26,0.12)',
  componentShadow: 'none',
  componentBg: '#FFFFFF',
  sectionPadding: '96px',
  contentGap: '28px',
  transitionDuration: '300ms',
  themeMode: 'light',
  extraTokens: {
    buttonStyle: 'outline',
    buttonRadius: '0px',
    ctaShadow: 'none',
    sectionBgAlternate: '#FAF6EF',
    containerMaxWidth: '1180px',
    headingWeight: '700',
    headingLetterSpacing: '-0.02em',
    gradientOverlay: 'none',
    overlayOpacity: '1',
    navbarHeight: '64px',
    countdownStyle: 'normal',
  },
};

const editorialTypography: TypographyVariant[] = [
  { name: 'Revista', headingScale: 1.2, bodyScale: 1.1, headingFont: 'Playfair Display', bodyFont: 'Lora' },
  { name: 'Prensa', headingScale: 1.15, bodyScale: 1.1, headingFont: 'Merriweather', bodyFont: 'Source Serif 4' },
  { name: 'Magazine', headingScale: 1.25, bodyScale: 1.1, headingFont: 'DM Serif Display', bodyFont: 'Inter' },
  { name: 'Crónica', headingScale: 1.2, bodyScale: 1.12, headingFont: 'Cormorant Garamond', bodyFont: 'Source Sans 3' },
  { name: 'Feature', headingScale: 1.25, bodyScale: 1.1, headingFont: 'Fraunces', bodyFont: 'Inter' },
  { name: 'Ensayo', headingScale: 1.2, bodyScale: 1.1, headingFont: 'EB Garamond', bodyFont: 'Jost' },
  { name: 'Periodístico', headingScale: 1.1, bodyScale: 1.1, headingFont: 'Libre Baskerville', bodyFont: 'Source Sans 3' },
  { name: 'Reportaje', headingScale: 1.2, bodyScale: 1.1, headingFont: 'Bitter', bodyFont: 'Inter' },
];

const editorialColorProposals: ColorPalette[] = [
  { name: 'Papel y Tinta', primary: '#241F1A', secondary: '#FAF6EF', accent: '#B23A2E' },
  { name: 'Periódico', primary: '#1E1E1E', secondary: '#F5F3EE', accent: '#0F4C81' },
  { name: 'Antiguo', primary: '#2E2419', secondary: '#F3E9D7', accent: '#8C6D3F' },
  { name: 'Manuscrito', primary: '#221C14', secondary: '#F8F2E6', accent: '#7A3B2E' },
  { name: 'Tinta Verde', primary: '#1C2620', secondary: '#F4F0E6', accent: '#3E5F43' },
  { name: 'Editorial Rojo', primary: '#231A1A', secondary: '#F7F2EC', accent: '#A63D2F' },
  { name: 'Serigrafía', primary: '#26201A', secondary: '#F0EEE9', accent: '#3F51B5' },
  { name: 'Tostado', primary: '#2B2014', secondary: '#F6EFE2', accent: '#B0753A' },
];

const editorialBrands: StyleBrand[] = [
  {
    name: 'Papel y Tinta',
    description: 'Serif editorial sobre papel: narrativa y profundidad.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(178,58,46,0.2)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '28px',
      transitionDuration: '300ms',
      themeMode: 'light',
    },
    typography: { name: 'Revista', headingScale: 1.2, bodyScale: 1.1, headingFont: 'Playfair Display', bodyFont: 'Lora' },
    palette: { name: 'Papel y Tinta', primary: '#241F1A', secondary: '#FAF6EF', accent: '#B23A2E' },
  },
  {
    name: 'Redacción',
    description: 'Tinta azul clásica: seriedad periodística y autoridad.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(15,76,129,0.2)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '28px',
      transitionDuration: '300ms',
      themeMode: 'light',
    },
    typography: { name: 'Prensa', headingScale: 1.15, bodyScale: 1.1, headingFont: 'Merriweather', bodyFont: 'Source Serif 4' },
    palette: { name: 'Periódico', primary: '#1E1E1E', secondary: '#F5F3EE', accent: '#0F4C81' },
  },
  {
    name: 'Archivo',
    description: 'Ocre antiguo y serif clásico: historias que perduran.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(140,109,63,0.22)',
      componentShadow: 'none',
      componentBg: '#F3E9D7',
      sectionPadding: '96px',
      contentGap: '28px',
      transitionDuration: '320ms',
      themeMode: 'light',
    },
    typography: { name: 'Crónica', headingScale: 1.2, bodyScale: 1.12, headingFont: 'Cormorant Garamond', bodyFont: 'Source Sans 3' },
    palette: { name: 'Antiguo', primary: '#2E2419', secondary: '#F3E9D7', accent: '#8C6D3F' },
  },
  {
    name: 'Reportaje',
    description: 'Rojo editorial sobre blanco: intensidad y emoción.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(166,61,47,0.2)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '28px',
      transitionDuration: '300ms',
      themeMode: 'light',
    },
    typography: { name: 'Feature', headingScale: 1.25, bodyScale: 1.1, headingFont: 'Fraunces', bodyFont: 'Inter' },
    palette: { name: 'Editorial Rojo', primary: '#231A1A', secondary: '#F7F2EC', accent: '#A63D2F' },
  },
  {
    name: 'Cuaderno',
    description: 'Verde natural y tinta: transformación orgánica y cercana.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(62,95,67,0.2)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '28px',
      transitionDuration: '300ms',
      themeMode: 'light',
    },
    typography: { name: 'Magazine', headingScale: 1.25, bodyScale: 1.1, headingFont: 'DM Serif Display', bodyFont: 'Inter' },
    palette: { name: 'Tinta Verde', primary: '#1C2620', secondary: '#F4F0E6', accent: '#3E5F43' },
  },
];

export const editorialStyle: LandingStyle = {
  id: 'editorial',
  name: 'Editorial',
  description: 'Narrativa de revista: tipografía serif, jerarquía editorial y storytelling profundo.',
  thumbnail: '/styles/editorial-thumb.svg',
  group: 'storytelling',
  allowedSubscriptions: ['starter', 'pro', 'premium'],
  layout: 'asymmetric',
  tokens: editorialBaseTokens,
  typography: editorialTypography,
  brands: editorialBrands,
  availableSections: [
    {
      id: 'heroVideo',
      name: 'Apertura Editorial',
      description: 'Redacta una apertura editorial: titular potente, bajada con profundidad y CTA. Tono narrativo y genuino, con promesa clara.',
      blueprint: 'Composición asimétrica: titular grande en serif a la izquierda, texto de apoyo en columna estrecha, CTA sobrio. Mucho aire, línea de detalle abajo.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'narrativeSections',
      name: 'Capítulos',
      description: 'Escribe capítulos de la historia del alumno: el antes, el giro y el después. Cada sección con aprendizajes concretos.',
      blueprint: 'Capítulos numerados con título en serif grande y cuerpo en columna de lectura. Numeración editorial en acento.',
      required: true, isRepeatable: true, contentType: 'text',
    },
    {
      id: 'benefits',
      name: 'Transformaciones',
      description: 'Presenta beneficios como transformaciones vividas: estado inicial y estado final.',
      blueprint: 'Bloques alternados en zigzag, texto amplio, sin tarjetas cerradas.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'syllabus',
      name: 'Temario Narrado',
      description: 'Describe el temario como capítulos de una historia: cada módulo como un avance de la transformación.',
      blueprint: 'Grilla editorial 2 columnas con números de módulo en serif.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'mentorProfile',
      name: 'El Autor',
      description: 'Presenta al mentor como autor: su historia, su oficio y por qué escribió este método.',
      blueprint: 'Retrato editorial a un lado, biografía narrativa al otro.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'testimonials',
      name: 'Historias de Lectores',
      description: 'Redacta 3-6 testimonios con estructura de historia corta: contexto, giro, resultado.',
      blueprint: 'Citas en serif itálica grande, cita central de la historia en negrita.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'bonuses',
      name: 'Material Complementario',
      description: 'Describe material adicional: guías, plantillas, recursos descargables.',
      blueprint: 'Lista editorial con íconos outline, texto descriptivo amplio.',
      required: false, isRepeatable: true, contentType: 'mixed',
    },
    {
      id: 'guarantee',
      name: 'Garantía',
      description: 'Garantía clara y honesta: plazo exacto y devolución total.',
      blueprint: 'Bloque centrado de texto serif, sin sello exagerado.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'faqs',
      name: 'Notas al Pie',
      description: 'Responde objeciones de lectores: para quién es, cuánto tiempo, qué incluye.',
      blueprint: 'Acordeones de texto puro con números editoriales.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'countdownTimer',
      name: 'Edición Limitada',
      description: 'Urgencia honesta: cierre de admisión o cupos de la edición.',
      blueprint: 'Barra fina con fondo de acento, reloj discreto.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'footer',
      name: 'Colofón',
      description: 'Disclaimer formal, copyright editorial y contacto.',
      blueprint: 'Texto small centrado sobre papel, aviso legal en 1 línea.',
      required: false, isRepeatable: false, contentType: 'text',
    },
  ],
  defaultVisibility: {
    heroVideo: true,
    narrativeSections: true,
    benefits: true,
    syllabus: true,
    mentorProfile: true,
    testimonials: false,
    bonuses: false,
    guarantee: true,
    faqs: false,
    countdownTimer: false,
    footer: true,
  },
  colorProposals: editorialColorProposals,
  aiDirectives: 'Eres un escritor editorial de revistas. Tono narrativo, genuino y con profundidad: cada sección cuenta una historia corta con giro y aprendizaje. Nunca prometas resultados garantizados.',
  aiWriterPersona: 'Escritor editorial. Estructura todo como relato: contexto, conflicto, transformación. Lenguaje cuidado y honesto, sin jerga de ventas.',
};
