import { LandingStyle, StyleBrand, StyleTokens, TypographyVariant, ColorPalette } from './types';

const executiveDarkBaseTokens: StyleTokens = {
  componentRadius: '8px',
  componentBorder: '1px solid rgba(148,163,184,0.14)',
  componentShadow: 'none',
  componentBg: 'rgba(148,163,184,0.06)',
  sectionPadding: '100px',
  contentGap: '24px',
  transitionDuration: '250ms',
  themeMode: 'dark',
  extraTokens: {
    buttonStyle: 'ghost',
    buttonRadius: '12px',
    ctaShadow: '0 0 30px rgba(56,192,255,0.35)',
    sectionBgAlternate: '#0A0E17',
    containerMaxWidth: '1180px',
    headingWeight: '600',
    headingLetterSpacing: '0em',
    gradientOverlay: 'linear-gradient(135deg, rgba(56,192,255,0.12), rgba(139,92,246,0.12))',
    overlayOpacity: '0.6',
    navbarHeight: '64px',
    countdownStyle: 'boxed',
  },
};

const executiveDarkTypography: TypographyVariant[] = [
  { name: 'Ejecutivo', headingScale: 1.2, bodyScale: 1.0, headingFont: 'Inter', bodyFont: 'Inter' },
  { name: 'C-Suite', headingScale: 1.25, bodyScale: 1.0, headingFont: 'Public Sans', bodyFont: 'Inter' },
  { name: 'Alta Dirección', headingScale: 1.2, bodyScale: 1.05, headingFont: 'Libre Baskerville', bodyFont: 'Inter' },
  { name: 'Capital', headingScale: 1.2, bodyScale: 1.0, headingFont: 'IBM Plex Sans', bodyFont: 'IBM Plex Sans' },
  { name: 'Estratega', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Manrope', bodyFont: 'Manrope' },
  { name: 'Mercado', headingScale: 1.25, bodyScale: 1.05, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
  { name: 'Inversor', headingScale: 1.25, bodyScale: 1.05, headingFont: 'Spectral', bodyFont: 'Inter' },
  { name: 'Mandato', headingScale: 1.2, bodyScale: 1.0, headingFont: 'Sora', bodyFont: 'Inter' },
];

const executiveDarkColorProposals: ColorPalette[] = [
  { name: 'Mercado Nocturno', primary: '#0A0E17', secondary: '#E2E8F0', accent: '#38BDF8' },
  { name: 'Capital Verde', primary: '#06120C', secondary: '#D1FAE5', accent: '#34D399' },
  { name: 'Fusión Violeta', primary: '#0B0713', secondary: '#EDE9FE', accent: '#8B5CF6' },
  { name: 'Riesgo Rojo', primary: '#120608', secondary: '#FEE2E2', accent: '#FB7185' },
  { name: 'Oro de Inversión', primary: '#120F04', secondary: '#FEF3C7', accent: '#FBBF24' },
  { name: 'Accionista Azul', primary: '#060B17', secondary: '#DBEAFE', accent: '#60A5FA' },
  { name: 'Directorio Grafito', primary: '#0A0A0C', secondary: '#F1F5F9', accent: '#F59E0B' },
  { name: 'Crypto Cian', primary: '#02120F', secondary: '#CCFBF1', accent: '#2DD4BF' },
];

const executiveDarkBrands: StyleBrand[] = [
  {
    name: 'Sala de Juntas',
    description: 'Azul nocturno y cian: tono de inversión y alta dirección.',
    tokens: {
      componentRadius: '8px',
      componentBorder: '1px solid rgba(56,189,248,0.2)',
      componentShadow: 'none',
      componentBg: 'rgba(56,189,248,0.05)',
      sectionPadding: '100px',
      contentGap: '24px',
      transitionDuration: '250ms',
      themeMode: 'dark',
    },
    typography: { name: 'Ejecutivo', headingScale: 1.2, bodyScale: 1.0, headingFont: 'Inter', bodyFont: 'Inter' },
    palette: { name: 'Mercado Nocturno', primary: '#0A0E17', secondary: '#E2E8F0', accent: '#38BDF8' },
  },
  {
    name: 'Capital Privado',
    description: 'Verde financiero sobre negro: rendimiento y valor.',
    tokens: {
      componentRadius: '8px',
      componentBorder: '1px solid rgba(52,211,153,0.2)',
      componentShadow: 'none',
      componentBg: 'rgba(52,211,153,0.05)',
      sectionPadding: '100px',
      contentGap: '24px',
      transitionDuration: '250ms',
      themeMode: 'dark',
    },
    typography: { name: 'Inversor', headingScale: 1.25, bodyScale: 1.05, headingFont: 'Spectral', bodyFont: 'Inter' },
    palette: { name: 'Capital Verde', primary: '#06120C', secondary: '#D1FAE5', accent: '#34D399' },
  },
  {
    name: 'Fondo Indexado',
    description: 'Violeta profundo: estrategia y análisis de mercado.',
    tokens: {
      componentRadius: '8px',
      componentBorder: '1px solid rgba(139,92,246,0.2)',
      componentShadow: 'none',
      componentBg: 'rgba(139,92,246,0.05)',
      sectionPadding: '100px',
      contentGap: '24px',
      transitionDuration: '250ms',
      themeMode: 'dark',
    },
    typography: { name: 'C-Suite', headingScale: 1.25, bodyScale: 1.0, headingFont: 'Public Sans', bodyFont: 'Inter' },
    palette: { name: 'Fusión Violeta', primary: '#0B0713', secondary: '#EDE9FE', accent: '#8B5CF6' },
  },
  {
    name: 'Alta Gerencia',
    description: 'Oro sobre grafito: exclusividad y resultados premium.',
    tokens: {
      componentRadius: '6px',
      componentBorder: '1px solid rgba(251,191,36,0.25)',
      componentShadow: 'none',
      componentBg: 'rgba(251,191,36,0.05)',
      sectionPadding: '100px',
      contentGap: '24px',
      transitionDuration: '250ms',
      themeMode: 'dark',
    },
    typography: { name: 'Estratega', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Manrope', bodyFont: 'Manrope' },
    palette: { name: 'Oro de Inversión', primary: '#120F04', secondary: '#FEF3C7', accent: '#FBBF24' },
  },
  {
    name: 'Sala de Trading',
    description: 'Cian crypto sobre negro: velocidad y momentum.',
    tokens: {
      componentRadius: '10px',
      componentBorder: '1px solid rgba(45,212,191,0.2)',
      componentShadow: '0 0 30px rgba(45,212,191,0.06)',
      componentBg: 'rgba(45,212,191,0.05)',
      sectionPadding: '100px',
      contentGap: '24px',
      transitionDuration: '220ms',
      themeMode: 'dark',
    },
    typography: { name: 'Mercado', headingScale: 1.25, bodyScale: 1.05, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
    palette: { name: 'Crypto Cian', primary: '#02120F', secondary: '#CCFBF1', accent: '#2DD4BF' },
  },
];

export const executiveDarkStyle: LandingStyle = {
  id: 'executive-dark',
  name: 'Executive Dark',
  description: 'Ejecutivo tech B2B en modo oscuro: cifras, precisión y acentos neón sobre negro.',
  thumbnail: '/styles/executive-dark-thumb.svg',
  group: 'high-ticket',
  allowedSubscriptions: ['pro', 'premium'],
  layout: 'split',
  tokens: executiveDarkBaseTokens,
  typography: executiveDarkTypography,
  brands: executiveDarkBrands,
  availableSections: [
    {
      id: 'heroVideo',
      name: 'Hero Ejecutivo',
      description: 'Redacta un hero de alto nivel: el resultado estratégico que el programa entrega a profesionales senior. Tono seguro y sobrio, sin promesas infladas.',
      blueprint: 'Split asimétrico sobre fondo oscuro: izquierda H1 en primario claro, subhead, CTA sobrio (ghost o filled), derecha visual de datos o video. Acento neón puntual.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'narrativeSections',
      name: 'Persuasión Estratégica',
      description: 'Argumenta a nivel estratégico: costo de oportunidad, posicionamiento y retorno. Viñetas cortas y precisas.',
      blueprint: 'Bloques estrechos de texto sobre negro. Títulos claros, cifras destacadas en mono con acento neón. Sin excesos.',
      required: true, isRepeatable: true, contentType: 'text',
    },
    {
      id: 'benefits',
      name: 'Ventajas Ejecutivas',
      description: 'Enumera ventajas de alto valor: tiempo, acceso exclusivo, red de contactos senior. Concretas y medibles.',
      blueprint: 'Lista vertical minimalista con íconos outline y texto amplio. Sin tarjetas cerradas.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'syllabus',
      name: 'Itinerario',
      description: 'Describe el itinerario como un recorrido de maestría: etapas con resultados concretos.',
      blueprint: 'Grilla sobria 2 columnas, títulos claros, separadores finos de acento.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'mentorProfile',
      name: 'Perfil del Líder',
      description: 'Presenta al mentor con autoridad: trayectoria, resultados y círculo de influencia.',
      blueprint: 'Foto en blanco y negro a un lado, biografía sobria al otro. Insignias de autoridad.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'testimonials',
      name: 'Resultados Senior',
      description: 'Redacta 3-6 testimonios con resultado concreto y perfil profesional del alumno.',
      blueprint: 'Citas asimétricas con resultado en mono destacado y nombre/rol abajo.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'bonuses',
      name: 'Accesos Exclusivos',
      description: 'Describe accesos adicionales (comunidad privada, sesiones 1:1, herramientas) con valor.',
      blueprint: 'Tarjetas oscuras con recurso a la izquierda y descripción a la derecha.',
      required: false, isRepeatable: true, contentType: 'mixed',
    },
    {
      id: 'guarantee',
      name: 'Garantía',
      description: 'Garantía contundente y formal: plazo exacto y devolución total.',
      blueprint: 'Bloque centrado con sello minimalista, texto formal corto.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'faqs',
      name: 'Preguntas Senior',
      description: 'Responde objeciones de profesionales: tiempo, retorno, exclusividad, forma de pago.',
      blueprint: 'Acordeones de texto puro, sin cajas, opacidad sutil al abrir.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'countdownTimer',
      name: 'Oportunidad Limitada',
      description: 'Urgencia real y sobria: cupos limitados o plazo de admisión.',
      blueprint: 'Barra sutil con fondo accent oscuro, reloj de dígitos sobrio.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'footer',
      name: 'Pie de Página',
      description: 'Disclaimer formal, copyright y datos de contacto.',
      blueprint: 'Texto centrado small sobre fondo primary oscuro.',
      required: false, isRepeatable: false, contentType: 'text',
    },
  ],
  defaultVisibility: {
    heroVideo: true,
    narrativeSections: true,
    benefits: true,
    syllabus: true,
    mentorProfile: true,
    testimonials: false,
    bonuses: true,
    guarantee: true,
    faqs: false,
    countdownTimer: false,
    footer: true,
  },
  colorProposals: executiveDarkColorProposals,
  aiDirectives: 'Eres un redactor ejecutivo de alto nivel. Tono seguro, sobrio y concreto: cada beneficio se traduce en valor estratégico o retorno medible. Sin promesas infladas ni falsa urgencia.',
  aiWriterPersona: 'Copywriter executive. Escribe para profesionales senior: claro, preciso y sin ruido. Autoridad tranquila, datos y exclusividad como argumento.',
};
