import { LandingStyle, StyleBrand, StyleTokens, TypographyVariant, ColorPalette } from './types';

const flashSaleBaseTokens: StyleTokens = {
  componentRadius: '18px',
  componentBorder: 'none',
  componentShadow: '0 6px 0 var(--primary)',
  componentBg: '#FFFFFF',
  sectionPadding: '96px',
  contentGap: '24px',
  transitionDuration: '200ms',
  themeMode: 'light',
  extraTokens: {
    buttonStyle: 'pill',
    buttonRadius: '9999px',
    ctaShadow: '0 10px 0 var(--primary)',
    sectionBgAlternate: '#FFF1E5',
    containerMaxWidth: '1180px',
    headingWeight: '600',
    headingLetterSpacing: '0em',
    gradientOverlay: 'none',
    overlayOpacity: '0.5',
    navbarHeight: '56px',
    countdownStyle: 'boxed',
  },
};

const flashSaleTypography: TypographyVariant[] = [
  { name: 'Impacto', headingScale: 1.25, bodyScale: 1.05, headingFont: 'Archivo', bodyFont: 'Inter' },
  { name: 'Grotesk Contundente', headingScale: 1.3, bodyScale: 1.05, headingFont: 'Archivo Black', bodyFont: 'Inter' },
  { name: 'Condensado Deportivo', headingScale: 1.3, bodyScale: 1.0, headingFont: 'Anton', bodyFont: 'Archivo' },
  { name: 'Neo Grotesk', headingScale: 1.2, bodyScale: 1.05, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
  { name: 'Geométrico Amplio', headingScale: 1.2, bodyScale: 1.0, headingFont: 'Chivo', bodyFont: 'Chivo' },
  { name: 'Sans Humanista', headingScale: 1.15, bodyScale: 1.1, headingFont: 'Sora', bodyFont: 'Inter' },
  { name: 'Alto Impacto', headingScale: 1.4, bodyScale: 1.0, headingFont: 'Bebas Neue', bodyFont: 'Barlow' },
  { name: 'Urbano', headingScale: 1.25, bodyScale: 1.1, headingFont: 'Archivo', bodyFont: 'Work Sans' },
];

const flashSaleColorProposals: ColorPalette[] = [
  { name: 'Ébano y Naranja', primary: '#0E0E0F', secondary: '#FFF9F2', accent: '#FF4D00' },
  { name: 'Sangre y Plata', primary: '#101014', secondary: '#FFFFFF', accent: '#E63C2E' },
  { name: 'Hora Dorada', primary: '#101014', secondary: '#FFF8E0', accent: '#FFC300' },
  { name: 'Dólar Verde', primary: '#0F1F14', secondary: '#F4FFF6', accent: '#00C267' },
  { name: 'Azul Adrenalina', primary: '#0B1220', secondary: '#F4F7FF', accent: '#1E9FFF' },
  { name: 'Magenta Promo', primary: '#160B14', secondary: '#FFF4FB', accent: '#FF2E97' },
  { name: 'Lima Eléctrica', primary: '#121208', secondary: '#F8F8E8', accent: '#C7F22F' },
  { name: 'Cian Descuento', primary: '#08141A', secondary: '#F0FAFF', accent: '#00D4FF' },
];

const flashSaleBrands: StyleBrand[] = [
  {
    name: 'Ébano y Naranja',
    description: 'Oferta relámpago clásica: fondo crema, naranja eléctrico y negro carbón. El pack aprobado en la demo.',
    tokens: {
      componentRadius: '18px',
      componentBorder: 'none',
      componentShadow: '0 6px 0 var(--primary)',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '24px',
      transitionDuration: '200ms',
      themeMode: 'light',
    },
    typography: { name: 'Impacto', headingScale: 1.25, bodyScale: 1.05, headingFont: 'Archivo', bodyFont: 'Inter' },
    palette: { name: 'Ébano y Naranja', primary: '#0E0E0F', secondary: '#FFF9F2', accent: '#FF4D00' },
  },
  {
    name: 'Liquidación Total',
    description: 'Todo en rojo y blanco: liquidación de cierre, urgencia máxima.',
    tokens: {
      componentRadius: '14px',
      componentBorder: '2px solid var(--primary)',
      componentShadow: '0 8px 0 var(--primary)',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '20px',
      transitionDuration: '180ms',
      themeMode: 'light',
    },
    typography: { name: 'Neo Grotesk', headingScale: 1.2, bodyScale: 1.05, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
    palette: { name: 'Sangre y Plata', primary: '#101014', secondary: '#FFFFFF', accent: '#E63C2E' },
  },
  {
    name: 'Oferta del Día',
    description: 'Cálido y dorado: oferta del día tipo club de beneficios.',
    tokens: {
      componentRadius: '22px',
      componentBorder: 'none',
      componentShadow: '0 6px 0 var(--primary)',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '28px',
      transitionDuration: '250ms',
      themeMode: 'light',
    },
    typography: { name: 'Condensado Deportivo', headingScale: 1.3, bodyScale: 1.0, headingFont: 'Anton', bodyFont: 'Archivo' },
    palette: { name: 'Hora Dorada', primary: '#101014', secondary: '#FFF8E0', accent: '#FFC300' },
  },
  {
    name: 'Dólar Verde',
    description: 'Descuento asociado al dinero: claro, fresco y de confianza.',
    tokens: {
      componentRadius: '16px',
      componentBorder: 'none',
      componentShadow: '0 6px 0 var(--primary)',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '24px',
      transitionDuration: '200ms',
      themeMode: 'light',
    },
    typography: { name: 'Sans Humanista', headingScale: 1.15, bodyScale: 1.1, headingFont: 'Sora', bodyFont: 'Inter' },
    palette: { name: 'Dólar Verde', primary: '#0F1F14', secondary: '#F4FFF6', accent: '#00C267' },
  },
  {
    name: 'Neón Nocturno',
    description: 'Lanzamiento a medianoche: verde lima eléctrico sobre carbón.',
    tokens: {
      componentRadius: '12px',
      componentBorder: '1px solid rgba(255,255,255,0.12)',
      componentShadow: '0 8px 0 var(--accent)',
      componentBg: '#15150C',
      sectionPadding: '104px',
      contentGap: '24px',
      transitionDuration: '200ms',
      themeMode: 'dark',
    },
    typography: { name: 'Alto Impacto', headingScale: 1.4, bodyScale: 1.0, headingFont: 'Bebas Neue', bodyFont: 'Barlow' },
    palette: { name: 'Lima Eléctrica', primary: '#121208', secondary: '#F8F8E8', accent: '#C7F22F' },
  },
];

export const flashSaleStyle: LandingStyle = {
  id: 'flash-sale',
  name: 'Flash Sale',
  description: 'Oferta por tiempo limitado. Alto contraste, urgencia visual, CTAs pill con sombra dura y countdown real.',
  thumbnail: '/styles/flash-sale-thumb.svg',
  group: 'promo',
  allowedSubscriptions: ['free', 'pro', 'premium'],
  layout: 'asymmetric',
  tokens: flashSaleBaseTokens,
  typography: flashSaleTypography,
  brands: flashSaleBrands,
  availableSections: [
    {
      id: 'offerBanner',
      name: 'Banner de Oferta',
      description: 'Escribe una línea corta de oferta superior con el plazo exacto (ej. "OFERTA TERMINA HOY") y la cifra del descuento. Urgente pero honesta, sin falsa escasez.',
      blueprint: 'Franja delgada de ancho completo en fondo accent, texto en uppercase blanco con letter-spacing, countdown compacto a la derecha. Altura ~44px, sticky arriba.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'heroVideo',
      name: 'Hero de Oferta',
      description: 'Redacta el titular de oferta con precio anclado: qué recibe, cuánto valía, cuánto paga hoy y en cuánto tiempo caduca. OBLIGATORIO: precio viejo tachado + precio de hoy + plazo. Confianza inmediata con garantía visible.',
      blueprint: 'Split asimétrico: izquierda copy (eyebrow en mono, H1 enorme en font-black, bullets de lo que incluye, CTA pill grande con sombra dura offset 10px, sello de garantía chico), derecha imagen vertical rotada levemente con sticker de oferta superpuesto.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'marquee',
      name: 'Cinta de Urgencia',
      description: 'Escribe 4-6 claims cortos de la oferta separados por separadores (ej. "ACCESO INMEDIATO • PAGO ÚNICO • GARANTÍA 7 DÍAS"). Beneficios concretos, sin adjetivos vacíos.',
      blueprint: 'Cinta horizontal infinita con texto en uppercase blanco sobre fondo accent o primary. Items separados por puntos o asteriscos. Altura ~48px, sin tarjetas.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'stats',
      name: 'Cifras de Prueba',
      description: 'Escribe 3-4 métricas reales de resultado (alumnos, satisfacción, resultados promedio). Solo números ciertos; si no hay métricas reales, usa etiqueta clara de ejemplo.',
      blueprint: 'Fila de 3-4 bloques con número gigante en mono font-black y etiqueta uppercase debajo. Fondo surface, separación por líneas finas, sin cajas.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'syllabus',
      name: 'Temario Expreso',
      description: 'Describe el temario como un atajo: módulos cortos y accionables ("Módulo 1: Tu oferta irresistible"). Cada módulo con resultado concreto al final.',
      blueprint: 'Lista numerada en 2 columnas. Número en mono grande, título en font-bold, descripción breve. Separadores de línea, sin cajas cerradas.',
      required: true, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'guarantee',
      name: 'Garantía Sin Riesgo',
      description: 'Redacta la garantía en 1 párrafo: riesgo cero, plazo exacto de prueba y promesa de devolución total. Elimina la objeción del precio.',
      blueprint: 'Bloque centrado con sello circular de garantía (borde accent, texto en círculo) + título corto y 1-2 líneas. Fondo sectionBgAlternate.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'bonuses',
      name: 'Bonos de Valor',
      description: 'Describe 2-4 bonos con valor monetizado tachado (ej. "BONO 1: Plantillas listas (valor $47) — HOY GRATIS"). Cada bono: nombre corto + beneficio en 1 línea + valor tachado.',
      blueprint: 'Tarjetas apiladas con mockup a la izquierda y texto a la derecha. Badge "BONO N" en accent, valor tachado en mono, sombra dura.',
      required: false, isRepeatable: true, contentType: 'mixed',
    },
    {
      id: 'testimonials',
      name: 'Prueba Social',
      description: 'Escribe 3-6 testimonios con resultado medible y nombre/rol del alumno. Transformación concreta en 1-2 líneas.',
      blueprint: 'Grilla asimétrica de tarjetas con resultado destacado en mono y cita corta. Avatar circular pequeño. Leve rotación alternada en algunas tarjetas.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'faqs',
      name: 'Preguntas de Compra',
      description: 'Responde objeciones: precio, tiempo invertido, para quién es, garantía, forma de pago. Respuestas cortas y directas que cierren la venta.',
      blueprint: 'Acordeón de texto: pregunta en font-bold, respuesta colapsada, chevron. Fondo surface, bordes finos inferiores.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'countdownTimer',
      name: 'Countdown Final',
      description: 'Reafirma el plazo real de la oferta con countdown y un mensaje de última llamada honesto. Repite precio de hoy y CTA.',
      blueprint: 'Bloque central sobre fondo accent o sectionBgAlternate: contador de 4 cajas (días/horas/min/seg) en mono gigante, precio tachado → precio hoy, CTA pill gigante con sombra.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'footer',
      name: 'Pie de Página',
      description: 'Disclaimer breve: no hay resultados garantizados, copyright y redes sociales del mentor.',
      blueprint: 'Texto centrado en uppercase small con letter-spacing. Minimalista, sin deco.',
      required: false, isRepeatable: false, contentType: 'text',
    },
  ],
  defaultVisibility: {
    offerBanner: true,
    heroVideo: true,
    marquee: true,
    stats: false,
    syllabus: true,
    guarantee: true,
    bonuses: false,
    testimonials: false,
    faqs: false,
    countdownTimer: true,
    footer: true,
  },
  colorProposals: flashSaleColorProposals,
  aiDirectives: 'Eres un redactor de ofertas flash. Urgencia honesta: promesas concretas y verificables, plazos reales y cifras exactas. Cada titular debe leerse en 3 segundos: qué recibe, cuánto valía, cuánto paga hoy. Sin exageraciones ni falsa escasez.',
  aiWriterPersona: 'Copywriter de ofertas relámpago. Escribe corto, directo y con números. Tono de mercado: cercano, sin formalismos ni elitismo. Usa countdowns y plazos como herramientas reales de decisión, nunca como truco.',
};
