import { LandingStyle, StyleBrand, StyleTokens, TypographyVariant, ColorPalette } from './types';

const launchCountdownBaseTokens: StyleTokens = {
  componentRadius: '16px',
  componentBorder: '1px solid rgba(255,255,255,0.12)',
  componentShadow: '0 0 30px rgba(255,255,255,0.08)',
  componentBg: 'rgba(255,255,255,0.04)',
  sectionPadding: '96px',
  contentGap: '24px',
  transitionDuration: '300ms',
  themeMode: 'dark',
  extraTokens: {
    buttonStyle: 'filled',
    buttonRadius: '16px',
    ctaShadow: 'none',
    sectionBgAlternate: '#0A0A0F',
    containerMaxWidth: '1100px',
    headingWeight: '700',
    headingLetterSpacing: '-0.02em',
    gradientOverlay: 'radial-gradient(circle at top right, rgba(139,92,246,0.18), transparent 60%)',
    overlayOpacity: '0.6',
    navbarHeight: '60px',
    countdownStyle: 'boxed',
  },
};

const launchCountdownTypography: TypographyVariant[] = [
  { name: 'Cósmico', headingScale: 1.3, bodyScale: 1.0, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
  { name: 'Técnico', headingScale: 1.25, bodyScale: 1.0, headingFont: 'JetBrains Mono', bodyFont: 'Inter' },
  { name: 'Futurista', headingScale: 1.3, bodyScale: 1.05, headingFont: 'Sora', bodyFont: 'Space Grotesk' },
  { name: 'Órbita', headingScale: 1.4, bodyScale: 1.0, headingFont: 'Orbitron', bodyFont: 'Space Grotesk' },
  { name: 'Galáctico', headingScale: 1.2, bodyScale: 1.0, headingFont: 'Unbounded', bodyFont: 'Inter' },
  { name: 'Laser', headingScale: 1.3, bodyScale: 1.05, headingFont: 'Chakra Petch', bodyFont: 'Inter' },
  { name: 'Neo Grafito', headingScale: 1.15, bodyScale: 1.05, headingFont: 'Archivo', bodyFont: 'Inter' },
  { name: 'Estelar', headingScale: 1.2, bodyScale: 1.1, headingFont: 'Outfit', bodyFont: 'Inter' },
];

const launchCountdownColorProposals: ColorPalette[] = [
  { name: 'Medianoche Aurora', primary: '#0A0A0F', secondary: '#F4F4FF', accent: '#8B5CF6' },
  { name: 'Espacio Profundo', primary: '#05070D', secondary: '#EDF2FF', accent: '#38BDF8' },
  { name: 'Nebulosa Rosa', primary: '#12060F', secondary: '#FFF0F7', accent: '#F472B6' },
  { name: 'Láser Verde', primary: '#04100C', secondary: '#EAFFF7', accent: '#34D399' },
  { name: 'Relámpago Ámbar', primary: '#0F0A02', secondary: '#FFF6E5', accent: '#FBBF24' },
  { name: 'Luz Fría', primary: '#08080F', secondary: '#F0F2FF', accent: '#818CF8' },
  { name: 'Alfa Rojo', primary: '#10040A', secondary: '#FFF0F3', accent: '#FB7185' },
  { name: 'Plasma Cian', primary: '#020D14', secondary: '#E9FBFF', accent: '#22D3EE' },
];

const launchCountdownBrands: StyleBrand[] = [
  {
    name: 'Lanzamiento Cósmico',
    description: 'Launch premium en modo oscuro: violeta neón sobre grafito, countdown protagonista.',
    tokens: {
      componentRadius: '18px',
      componentBorder: '1px solid rgba(139,92,246,0.25)',
      componentShadow: '0 0 40px rgba(139,92,246,0.15)',
      componentBg: 'rgba(255,255,255,0.04)',
      sectionPadding: '104px',
      contentGap: '28px',
      transitionDuration: '300ms',
      themeMode: 'dark',
    },
    typography: { name: 'Cósmico', headingScale: 1.3, bodyScale: 1.0, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
    palette: { name: 'Medianoche Aurora', primary: '#0A0A0F', secondary: '#F4F4FF', accent: '#8B5CF6' },
  },
  {
    name: 'Noche Profunda',
    description: 'Cian sobre negro profundo: la cuenta regresiva de medianoche, mono y limpio.',
    tokens: {
      componentRadius: '12px',
      componentBorder: '1px solid rgba(56,189,248,0.25)',
      componentShadow: '0 0 24px rgba(56,189,248,0.12)',
      componentBg: 'rgba(255,255,255,0.03)',
      sectionPadding: '96px',
      contentGap: '24px',
      transitionDuration: '280ms',
      themeMode: 'dark',
    },
    typography: { name: 'Técnico', headingScale: 1.25, bodyScale: 1.0, headingFont: 'JetBrains Mono', bodyFont: 'Inter' },
    palette: { name: 'Espacio Profundo', primary: '#05070D', secondary: '#EDF2FF', accent: '#38BDF8' },
  },
  {
    name: 'Estreno Rosa',
    description: 'Rosa neón sobre grafito cálido: lanzamiento con personalidad y actitud.',
    tokens: {
      componentRadius: '20px',
      componentBorder: '1px solid rgba(244,114,182,0.25)',
      componentShadow: '0 0 40px rgba(244,114,182,0.14)',
      componentBg: 'rgba(255,255,255,0.04)',
      sectionPadding: '104px',
      contentGap: '28px',
      transitionDuration: '320ms',
      themeMode: 'dark',
    },
    typography: { name: 'Futurista', headingScale: 1.3, bodyScale: 1.05, headingFont: 'Sora', bodyFont: 'Space Grotesk' },
    palette: { name: 'Nebulosa Rosa', primary: '#12060F', secondary: '#FFF0F7', accent: '#F472B6' },
  },
  {
    name: 'Alfa Ámbar',
    description: 'Ámbar caliente sobre negro: teaser de alto impacto, tipografía ancha.',
    tokens: {
      componentRadius: '14px',
      componentBorder: '1px solid rgba(251,191,36,0.3)',
      componentShadow: '0 0 30px rgba(251,191,36,0.12)',
      componentBg: 'rgba(255,255,255,0.03)',
      sectionPadding: '96px',
      contentGap: '24px',
      transitionDuration: '260ms',
      themeMode: 'dark',
    },
    typography: { name: 'Neo Grafito', headingScale: 1.15, bodyScale: 1.05, headingFont: 'Archivo', bodyFont: 'Inter' },
    palette: { name: 'Relámpago Ámbar', primary: '#0F0A02', secondary: '#FFF6E5', accent: '#FBBF24' },
  },
  {
    name: 'Señal Verde',
    description: 'Láser verde sobre negro: estreno fresco y confiable, con glow techno.',
    tokens: {
      componentRadius: '10px',
      componentBorder: '1px solid rgba(52,211,153,0.3)',
      componentShadow: '0 0 30px rgba(52,211,153,0.15)',
      componentBg: 'rgba(255,255,255,0.03)',
      sectionPadding: '100px',
      contentGap: '26px',
      transitionDuration: '300ms',
      themeMode: 'dark',
    },
    typography: { name: 'Órbita', headingScale: 1.4, bodyScale: 1.0, headingFont: 'Orbitron', bodyFont: 'Space Grotesk' },
    palette: { name: 'Láser Verde', primary: '#04100C', secondary: '#EAFFF7', accent: '#34D399' },
  },
  {
    name: 'Plasma Cian',
    description: 'Cian plasma sobre azul noche: estreno digital, futurista y vibrante.',
    tokens: {
      componentRadius: '16px',
      componentBorder: '1px solid rgba(34,211,238,0.3)',
      componentShadow: '0 0 44px rgba(34,211,238,0.16)',
      componentBg: 'rgba(255,255,255,0.04)',
      sectionPadding: '104px',
      contentGap: '28px',
      transitionDuration: '300ms',
      themeMode: 'dark',
    },
    typography: { name: 'Laser', headingScale: 1.3, bodyScale: 1.05, headingFont: 'Chakra Petch', bodyFont: 'Inter' },
    palette: { name: 'Plasma Cian', primary: '#020D14', secondary: '#E9FBFF', accent: '#22D3EE' },
  },
];

export const launchCountdownStyle: LandingStyle = {
  id: 'launch-countdown',
  name: 'Launch Countdown',
  description: 'Lanzamiento y teaser en modo oscuro: el countdown es el protagonista, expectativa y exclusividad.',
  thumbnail: '/styles/launch-countdown-thumb.svg',
  group: 'promo',
  allowedSubscriptions: ['free', 'pro', 'premium'],
  layout: 'centered',
  tokens: launchCountdownBaseTokens,
  typography: launchCountdownTypography,
  brands: launchCountdownBrands,
  availableSections: [
    {
      id: 'offerBanner',
      name: 'Banner de Lanzamiento',
      description: 'Escribe la línea superior del estreno: aviso corto con la fecha exacta y la promesa de anticipación (ej. "LANZAMIENTO OFICIAL: 14 DE MARZO — RESERVA TU LUGAR"). Algo grande viene, sin falsas promesas.',
      blueprint: 'Franja delgada de ancho completo en fondo accent sobre modo oscuro, texto en uppercase claro con letter-spacing y leve glow. Altura ~44px, sticky arriba.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'heroVideo',
      name: 'Hero de Lanzamiento',
      description: 'Redacta el titular del estreno sin mostrar el producto completo (misterio controlado). OBLIGATORIO: fecha de lanzamiento concreta y CTA de reserva. Genera anticipación: "Lo que viene va a cambiar cómo aprendes X".',
      blueprint: 'Layout centrado o split asimétrico sobre fondo oscuro: eyebrow en mono con la fecha, H1 enorme font-black, subhead de expectativa, CTA luminoso (fondo accent) y countdown grande debajo. Imagen teaser enmarcada con glow. Alto contraste.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'marquee',
      name: 'Cinta de Expectativa',
      description: 'Escribe 4-6 claims del lanzamiento separados por separadores (ej. "ACCESO TEMPRANO • CUPOS LIMITADOS • BONOS DE LANZAMIENTO"). Expectativa y exclusividad, beneficios breves.',
      blueprint: 'Cinta horizontal infinita en uppercase sobre fondo oscuro, texto claro separado por puntos o asteriscos de accent. Altura ~48px, sin tarjetas.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'stats',
      name: 'Cifras de Expectativa',
      description: 'Presenta 3-4 métricas que generen deseo de estar primero (alumnos en lista de espera, resultados previos, % de éxito). Números exactos y honestos; si no hay dato real, placeholder claro.',
      blueprint: 'Fila de 3-4 cifras gigantes en tipografía mono sobre el fondo oscuro, etiqueta uppercase debajo. Sin cajas, separadas por líneas finas de accent.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'narrativeSections',
      name: 'Secciones de Expectativa',
      description: 'Escribe con el tono de quien anuncia el gran estreno: el problema, la promesa de transformación y por qué reservar YA (cupos de lanzamiento limitados). Viñetas cortas y una frase de exclusividad.',
      blueprint: 'Bloques de texto con alineación alternada sobre fondo oscuro. Viñetas con check de accent. Frase de exclusividad en chip pill con glow. Márgenes generosos.',
      required: true, isRepeatable: true, contentType: 'text',
    },
    {
      id: 'syllabus',
      name: 'Temario del Estreno',
      description: 'Describe el temario como la hoja de ruta de lo que se estrena: módulos cortos y accionables con logro concreto al terminar. Nombres que generen anticipación.',
      blueprint: 'Grilla numerada 2 columnas en modo oscuro. Número grande en accent (font-black), título font-bold, descripción de 1-2 líneas. Separadores de línea o tarjetas translúcidas con borde sutil.',
      required: true, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'guarantee',
      name: 'Garantía de Reserva',
      description: 'Redacta la garantía de riesgo cero para reservar: "Reserva hoy y si al estrenar no es para ti, te devolvemos el 100%". Plazo explícito y sin letra pequeña.',
      blueprint: 'Bloque centrado con sello circular de garantía (borde accent con glow) sobre fondo sectionBgAlternate oscuro. Texto en 2 líneas máximo.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'bonuses',
      name: 'Bonos de Lanzamiento',
      description: 'Apila 2-4 bonos solo para los primeros que reserven. OBLIGATORIO: valor monetizado tachado (ej. "BONO 1: Masterclass privada — $97 HOY GRATIS") y por qué se retiran al estrenar.',
      blueprint: 'Tarjetas apiladas en modo oscuro con mockup a la izquierda y descripción a la derecha. Precio tachado + GRATIS en accent (mono). Badge "BONO N" pill.',
      required: false, isRepeatable: true, contentType: 'mixed',
    },
    {
      id: 'testimonials',
      name: 'Expectativa de la Comunidad',
      description: 'Redacta 3-6 historias cortas de la comunidad que espera el lanzamiento o resultados previos, con resultado medible y nombre/rol. Que el lector se identifique.',
      blueprint: 'Grilla asimétrica de tarjetas oscuras con cita corta, resultado en mono destacado, avatar circular small. Leve rotación alternada.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'countdownTimer',
      name: 'Countdown del Estreno',
      description: 'El protagonista: cierra con el countdown final al estreno, la fecha exacta, un mensaje de anticipación y el CTA de reserva. OBLIGATORIO: countdown en vivo y un solo mensaje de escasez honesta.',
      blueprint: 'Bloque central enorme en modo oscuro: countdown de 4 cajas (días/horas/min/seg) en tipografía mono gigante con glow accent, fecha del estreno y CTA pill luminoso debajo. Fondo accent sutil o sectionBgAlternate oscuro.',
      required: true, isRepeatable: false, contentType: 'interactive',
    },
    {
      id: 'faqs',
      name: 'Preguntas del Lanzamiento',
      description: 'Responde objeciones de reserva: qué incluye, cuándo se estrena, precio, cupos, garantía, forma de pago. Respuestas cortas y directas que eliminen la fricción de reservar.',
      blueprint: 'Acordeón de texto sobre fondo oscuro. Pregunta font-bold con chevron, respuesta colapsable, separadores finos inferiores.',
      required: false, isRepeatable: false, contentType: 'interactive',
    },
    {
      id: 'footer',
      name: 'Pie de Lanzamiento',
      description: 'Disclaimer de resultados, copyright y cierre suave de anticipación: "El estreno está cerca. La decisión es tuya".',
      blueprint: 'Texto centrado small sobre fondo primary oscuro, aviso legal en 1 línea, minimalista.',
      required: false, isRepeatable: false, contentType: 'text',
    },
  ],
  defaultVisibility: {
    offerBanner: true,
    heroVideo: true,
    marquee: true,
    stats: false,
    narrativeSections: true,
    syllabus: true,
    guarantee: true,
    bonuses: true,
    testimonials: false,
    countdownTimer: true,
    faqs: false,
    footer: true,
  },
  colorProposals: launchCountdownColorProposals,
  aiDirectives: 'Eres el redactor del lanzamiento de un curso. Anticipación honesta: genera expectativa sin prometer de más. Cada titular debe comunicar que algo grande llega y por qué el lector debe reservar su lugar YA: fecha concreta, cupos limitados de lanzamiento, bonos solo para los primeros. Sin falsa escasez ni exageraciones.',
  aiWriterPersona: 'Copywriter de lanzamientos premium. Tono de misterio y exclusividad: cercano, seguro, sin ruido. Usa el countdown y la fecha de estreno como ancla real de decisión, nunca como truco.',
};
