import { LandingStyle, StyleBrand, StyleTokens, TypographyVariant, ColorPalette } from './types';

const luxurySerifBaseTokens: StyleTokens = {
  componentRadius: '0px',
  componentBorder: '1px solid rgba(120,95,44,0.25)',
  componentShadow: 'none',
  componentBg: '#FFFDF7',
  sectionPadding: '104px',
  contentGap: '28px',
  transitionDuration: '400ms',
  themeMode: 'light',
  extraTokens: {
    buttonStyle: 'outline',
    buttonRadius: '0px',
    ctaShadow: 'none',
    sectionBgAlternate: '#FFFDF7',
    containerMaxWidth: '1180px',
    headingWeight: '600',
    headingLetterSpacing: '0.01em',
    gradientOverlay: 'none',
    overlayOpacity: '1',
    navbarHeight: '64px',
    countdownStyle: 'normal',
  },
};

const luxurySerifTypography: TypographyVariant[] = [
  { name: 'Serif Imperial', headingScale: 1.25, bodyScale: 1.1, headingFont: 'Cormorant Garamond', bodyFont: 'Montserrat' },
  { name: 'Serif Editorial', headingScale: 1.2, bodyScale: 1.1, headingFont: 'Playfair Display', bodyFont: 'Lato' },
  { name: 'Serif Clásico', headingScale: 1.2, bodyScale: 1.05, headingFont: 'Libre Baskerville', bodyFont: 'Source Sans 3' },
  { name: 'Serif Real', headingScale: 1.3, bodyScale: 1.1, headingFont: 'EB Garamond', bodyFont: 'Jost' },
  { name: 'Serif Antiguo', headingScale: 1.25, bodyScale: 1.05, headingFont: 'Marcellus', bodyFont: 'Inter' },
  { name: 'Serif Refinado', headingScale: 1.3, bodyScale: 1.1, headingFont: 'Italiana', bodyFont: 'Montserrat' },
  { name: 'Boutique', headingScale: 1.2, bodyScale: 1.1, headingFont: 'Fraunces', bodyFont: 'Inter' },
  { name: 'Galería', headingScale: 1.25, bodyScale: 1.05, headingFont: 'Prata', bodyFont: 'Inter' },
];

const luxurySerifColorProposals: ColorPalette[] = [
  { name: 'Oro y Crema', primary: '#3F2E1E', secondary: '#FFFDF7', accent: '#C9A227' },
  { name: 'Marfil y Bronce', primary: '#2B2118', secondary: '#FBF7EF', accent: '#B08D57' },
  { name: 'Champán', primary: '#433018', secondary: '#FDF9EF', accent: '#D4AF37' },
  { name: 'Borgoña Imperial', primary: '#4A1B23', secondary: '#FBF4EF', accent: '#C5A059' },
  { name: 'Esmalte Verde', primary: '#1E3D33', secondary: '#F7F3E8', accent: '#B6A05C' },
  { name: 'Medianoche Añejo', primary: '#232A3E', secondary: '#F7F4EE', accent: '#C2A878' },
  { name: 'Cobre Tostado', primary: '#4E2A15', secondary: '#FAF5EE', accent: '#C7792D' },
  { name: 'Perla y Platino', primary: '#2F3137', secondary: '#F7F7F5', accent: '#C0B49A' },
];

const luxurySerifBrands: StyleBrand[] = [
  {
    name: 'Casa Real',
    description: 'Oro y crema con serif imperial: lujo clásico y atemporal.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(201,162,39,0.3)',
      componentShadow: 'none',
      componentBg: '#FFFDF7',
      sectionPadding: '104px',
      contentGap: '28px',
      transitionDuration: '400ms',
      themeMode: 'light',
    },
    typography: { name: 'Serif Imperial', headingScale: 1.25, bodyScale: 1.1, headingFont: 'Cormorant Garamond', bodyFont: 'Montserrat' },
    palette: { name: 'Oro y Crema', primary: '#3F2E1E', secondary: '#FFFDF7', accent: '#C9A227' },
  },
  {
    name: 'Alta Costura',
    description: 'Champán sobre marfil: exclusividad y refinamiento.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(212,175,55,0.35)',
      componentShadow: 'none',
      componentBg: '#FDF9EF',
      sectionPadding: '108px',
      contentGap: '30px',
      transitionDuration: '400ms',
      themeMode: 'light',
    },
    typography: { name: 'Serif Refinado', headingScale: 1.3, bodyScale: 1.1, headingFont: 'Italiana', bodyFont: 'Montserrat' },
    palette: { name: 'Champán', primary: '#433018', secondary: '#FDF9EF', accent: '#D4AF37' },
  },
  {
    name: 'Herencia',
    description: 'Borgoña imperial con oro: tradición y prestigio.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(197,160,89,0.3)',
      componentShadow: 'none',
      componentBg: '#FBF4EF',
      sectionPadding: '104px',
      contentGap: '28px',
      transitionDuration: '400ms',
      themeMode: 'light',
    },
    typography: { name: 'Serif Clásico', headingScale: 1.2, bodyScale: 1.05, headingFont: 'Libre Baskerville', bodyFont: 'Source Sans 3' },
    palette: { name: 'Borgoña Imperial', primary: '#4A1B23', secondary: '#FBF4EF', accent: '#C5A059' },
  },
  {
    name: 'Atelier',
    description: 'Marfil y bronce: artesanía y edición de autor.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(176,141,87,0.3)',
      componentShadow: 'none',
      componentBg: '#FBF7EF',
      sectionPadding: '104px',
      contentGap: '28px',
      transitionDuration: '400ms',
      themeMode: 'light',
    },
    typography: { name: 'Boutique', headingScale: 1.2, bodyScale: 1.1, headingFont: 'Fraunces', bodyFont: 'Inter' },
    palette: { name: 'Marfil y Bronce', primary: '#2B2118', secondary: '#FBF7EF', accent: '#B08D57' },
  },
  {
    name: 'Club Privado',
    description: 'Medianoche añejo: elegancia sobria y reservada.',
    tokens: {
      componentRadius: '0px',
      componentBorder: '1px solid rgba(194,168,120,0.3)',
      componentShadow: 'none',
      componentBg: '#F7F4EE',
      sectionPadding: '108px',
      contentGap: '28px',
      transitionDuration: '450ms',
      themeMode: 'light',
    },
    typography: { name: 'Serif Editorial', headingScale: 1.2, bodyScale: 1.1, headingFont: 'Playfair Display', bodyFont: 'Lato' },
    palette: { name: 'Medianoche Añejo', primary: '#232A3E', secondary: '#F7F4EE', accent: '#C2A878' },
  },
];

export const luxurySerifStyle: LandingStyle = {
  id: 'luxury-serif',
  name: 'Luxury Serif',
  description: 'Lujo editorial: tipografía serif display, oro y crema, aire de alta gama.',
  thumbnail: '/styles/luxury-serif-thumb.svg',
  group: 'high-ticket',
  allowedSubscriptions: ['pro', 'premium'],
  layout: 'centered',
  tokens: luxurySerifBaseTokens,
  typography: luxurySerifTypography,
  brands: luxurySerifBrands,
  availableSections: [
    {
      id: 'heroVideo',
      name: 'Portada de Lujo',
      description: 'Redacta un titular de alto valor: el estatus y resultado exclusivo que se obtiene. Tono elegante y aspiracional, sin desesperación.',
      blueprint: 'Diseño ultra minimalista centrado: H1 en serif display grande, subhead breve, CTA outline sobrio. Fondo crema, mucho aire. Opcional visual editorial.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'narrativeSections',
      name: 'Carta del Fundador',
      description: 'Escribe en tono de carta personal de alto nivel: la filosofía, la promesa de transformación y por qué es una oportunidad única.',
      blueprint: 'Bloque estrecho de texto, tipografía con alto contraste, firma al final. Alineación izquierda con márgenes generosos.',
      required: true, isRepeatable: true, contentType: 'text',
    },
    {
      id: 'benefits',
      name: 'Privilegios',
      description: 'Enumera privilegios: acceso exclusivo, atención personalizada, red de contactos selecta.',
      blueprint: 'Lista minimalista con íconos outline delgados. Texto amplio y elegante.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'syllabus',
      name: 'Recorrido Exclusivo',
      description: 'Describe el temario como un recorrido exclusivo de maestría: etapas con lenguaje sofisticado.',
      blueprint: 'Grilla sobria 2 columnas, títulos en oro, separadores finos, sin cajas.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'mentorProfile',
      name: 'Perfil del Maestro',
      description: 'Presenta al mentor con autoridad elegante: trayectoria, prestigio y círculo de influencia.',
      blueprint: 'Foto editorial a un lado, biografía sofisticada al otro. Sin excesos.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'testimonials',
      name: 'Testimonios Distinguidos',
      description: 'Redacta 3-6 testimonios de clientes distinguidos con resultado concreto y nombre/rol.',
      blueprint: 'Citas en serif itálica gigante, nombre pequeño y elegante abajo. Sin fotos.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'bonuses',
      name: 'Obsequios',
      description: 'Describe obsequios de alto valor: sesiones 1:1, piezas editoriales, acceso anticipado.',
      blueprint: 'Tarjetas elegantes con recurso a la izquierda y descripción en serif a la derecha.',
      required: false, isRepeatable: true, contentType: 'mixed',
    },
    {
      id: 'guarantee',
      name: 'Garantía',
      description: 'Garantía formal y tranquila: plazo explícito y devolución total.',
      blueprint: 'Bloque centrado con sello minimalista, texto formal y corto.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'faqs',
      name: 'Preguntas Selectas',
      description: 'Responde objeciones con elegancia: valor, tiempo, exclusividad, acceso.',
      blueprint: 'Acordeones de texto puro, sin cajas, opacidad sutil.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'countdownTimer',
      name: 'Oportunidad Reservada',
      description: 'Urgencia sutil y elegante: cupos limitados o fecha de admisión.',
      blueprint: 'Barra sobria con acento dorado, reloj discreto.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'footer',
      name: 'Pie de Página',
      description: 'Disclaimer elegante, copyright y contacto.',
      blueprint: 'Texto centrado small, sobrio, aviso legal en 1 línea.',
      required: false, isRepeatable: false, contentType: 'text',
    },
  ],
  defaultVisibility: {
    heroVideo: true,
    narrativeSections: true,
    benefits: true,
    syllabus: true,
    mentorProfile: true,
    testimonials: false,
    bonuses: false,
    guarantee: true,
    faqs: false,
    countdownTimer: false,
    footer: true,
  },
  colorProposals: luxurySerifColorProposals,
  aiDirectives: 'Eres un redactor de lujo. Tono elegante, aspiracional y sereno: cada frase transmite exclusividad y valor, sin desesperación ni superlativos vacíos.',
  aiWriterPersona: 'Copywriter de alta gama. Escribe con refinamiento y autoridad tranquila. Menos palabras, más significado. El estatus y la calidad son el argumento.',
};
