import { LandingStyle, StyleBrand, StyleTokens, TypographyVariant, ColorPalette } from './types';

const modernCleanBaseTokens: StyleTokens = {
  componentRadius: '12px',
  componentBorder: '1px solid rgba(15,23,42,0.08)',
  componentShadow: '0 1px 2px rgba(15,23,42,0.04)',
  componentBg: '#FFFFFF',
  sectionPadding: '96px',
  contentGap: '24px',
  transitionDuration: '250ms',
  themeMode: 'light',
  extraTokens: {
    buttonStyle: 'filled',
    buttonRadius: '16px',
    ctaShadow: 'none',
    sectionBgAlternate: '#FFFFFF',
    containerMaxWidth: '1180px',
    headingWeight: '600',
    headingLetterSpacing: '-0.01em',
    gradientOverlay: 'none',
    overlayOpacity: '1',
    navbarHeight: '64px',
    countdownStyle: 'normal',
  },
};

const modernCleanTypography: TypographyVariant[] = [
  { name: 'Moderno', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Inter', bodyFont: 'Inter' },
  { name: 'Contemporáneo', headingScale: 1.2, bodyScale: 1.0, headingFont: 'Plus Jakarta Sans', bodyFont: 'Inter' },
  { name: 'Funcional', headingScale: 1.15, bodyScale: 1.05, headingFont: 'Manrope', bodyFont: 'Manrope' },
  { name: 'Neutral', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Public Sans', bodyFont: 'Public Sans' },
  { name: 'Simplificado', headingScale: 1.1, bodyScale: 1.0, headingFont: 'IBM Plex Sans', bodyFont: 'IBM Plex Sans' },
  { name: 'Suave', headingScale: 1.15, bodyScale: 1.05, headingFont: 'Sora', bodyFont: 'Inter' },
  { name: 'Ágil', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
  { name: 'Claro', headingScale: 1.1, bodyScale: 1.0, headingFont: 'Inter', bodyFont: 'Source Sans 3' },
];

const modernCleanColorProposals: ColorPalette[] = [
  { name: 'Blanco y Azul', primary: '#0F172A', secondary: '#FFFFFF', accent: '#2563EB' },
  { name: 'Nube y Índigo', primary: '#1E293B', secondary: '#F8FAFC', accent: '#6366F1' },
  { name: 'Claro y Esmeralda', primary: '#0F1F17', secondary: '#FCFDFD', accent: '#10B981' },
  { name: 'Minimal Negro', primary: '#111111', secondary: '#FFFFFF', accent: '#E11D48' },
  { name: 'Aire y Cian', primary: '#0B1120', secondary: '#F0F9FF', accent: '#06B6D4' },
  { name: 'Pastel Rosa', primary: '#1F2937', secondary: '#FFFBF7', accent: '#DB2777' },
  { name: 'Pizarra y Ámbar', primary: '#1C1917', secondary: '#FCFCFB', accent: '#F59E0B' },
  { name: 'Blanco y Violeta', primary: '#1E1B4B', secondary: '#FAFAFA', accent: '#7C3AED' },
];

const modernCleanBrands: StyleBrand[] = [
  {
    name: 'Blanco y Azul',
    description: 'Claro, limpio y confiable: azul sobre blanco.',
    tokens: {
      componentRadius: '12px',
      componentBorder: '1px solid rgba(37,99,235,0.15)',
      componentShadow: '0 1px 2px rgba(37,99,235,0.05)',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '24px',
      transitionDuration: '250ms',
      themeMode: 'light',
    },
    typography: { name: 'Moderno', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Inter', bodyFont: 'Inter' },
    palette: { name: 'Blanco y Azul', primary: '#0F172A', secondary: '#FFFFFF', accent: '#2563EB' },
  },
  {
    name: 'Nube y Índigo',
    description: 'Aire fresco y moderno: índigo suave sobre gris claro.',
    tokens: {
      componentRadius: '14px',
      componentBorder: '1px solid rgba(99,102,241,0.15)',
      componentShadow: '0 2px 8px rgba(99,102,241,0.06)',
      componentBg: '#FFFFFF',
      sectionPadding: '100px',
      contentGap: '24px',
      transitionDuration: '250ms',
      themeMode: 'light',
    },
    typography: { name: 'Contemporáneo', headingScale: 1.2, bodyScale: 1.0, headingFont: 'Plus Jakarta Sans', bodyFont: 'Inter' },
    palette: { name: 'Nube y Índigo', primary: '#1E293B', secondary: '#F8FAFC', accent: '#6366F1' },
  },
  {
    name: 'Claro y Esmeralda',
    description: 'Limpio y fresco: esmeralda sobre blanco natural.',
    tokens: {
      componentRadius: '12px',
      componentBorder: '1px solid rgba(16,185,129,0.15)',
      componentShadow: '0 1px 2px rgba(16,185,129,0.05)',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '24px',
      transitionDuration: '250ms',
      themeMode: 'light',
    },
    typography: { name: 'Funcional', headingScale: 1.15, bodyScale: 1.05, headingFont: 'Manrope', bodyFont: 'Manrope' },
    palette: { name: 'Claro y Esmeralda', primary: '#0F1F17', secondary: '#FCFDFD', accent: '#10B981' },
  },
  {
    name: 'Minimal Negro',
    description: 'Monocromo con acento rojo: moderno y audaz.',
    tokens: {
      componentRadius: '8px',
      componentBorder: '1px solid rgba(17,17,17,0.1)',
      componentShadow: 'none',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '24px',
      transitionDuration: '250ms',
      themeMode: 'light',
    },
    typography: { name: 'Simplificado', headingScale: 1.1, bodyScale: 1.0, headingFont: 'IBM Plex Sans', bodyFont: 'IBM Plex Sans' },
    palette: { name: 'Minimal Negro', primary: '#111111', secondary: '#FFFFFF', accent: '#E11D48' },
  },
  {
    name: 'Aire y Cian',
    description: 'Fresco y tecnológico: cian sobre cielo.',
    tokens: {
      componentRadius: '12px',
      componentBorder: '1px solid rgba(6,182,212,0.18)',
      componentShadow: '0 1px 3px rgba(6,182,212,0.06)',
      componentBg: '#FFFFFF',
      sectionPadding: '96px',
      contentGap: '24px',
      transitionDuration: '220ms',
      themeMode: 'light',
    },
    typography: { name: 'Ágil', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
    palette: { name: 'Aire y Cian', primary: '#0B1120', secondary: '#F0F9FF', accent: '#06B6D4' },
  },
];

export const modernCleanStyle: LandingStyle = {
  id: 'modern-clean',
  name: 'Modern Clean',
  description: 'Minimalismo moderno: fondo claro, tipografía sans, mucho aire y CTA limpio.',
  thumbnail: '/styles/modern-clean-thumb.svg',
  group: 'storytelling',
  allowedSubscriptions: ['starter', 'pro', 'premium'],
  layout: 'centered',
  tokens: modernCleanBaseTokens,
  typography: modernCleanTypography,
  brands: modernCleanBrands,
  availableSections: [
    {
      id: 'heroVideo',
      name: 'Hero Limpio',
      description: 'Redacta un hero claro y directo: titular que promete el resultado, subhead con detalle y CTA único. Tono cercano y moderno.',
      blueprint: 'Centrado y aireado: H1 grande en sans, subhead en columna estrecha, un CTA principal filled y uno secundario ghost. Visual limpio abajo.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'narrativeSections',
      name: 'Historia en Bloques',
      description: 'Explica el método y el porqué en bloques claros: problema, solución y proceso. Lenguaje simple y honesto.',
      blueprint: 'Secciones con encabezado corto y párrafo en columna de lectura. Sin jerga.',
      required: true, isRepeatable: true, contentType: 'text',
    },
    {
      id: 'benefits',
      name: 'Beneficios',
      description: 'Enumera beneficios claros y concretos: qué obtiene y cómo cambia su día a día.',
      blueprint: 'Grilla 3 columnas de tarjetas suaves con ícono, título corto y texto breve.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'syllabus',
      name: 'Programa',
      description: 'Describe el programa en módulos claros: qué aprende y en qué tiempo.',
      blueprint: 'Grilla limpia 2 columnas con tarjetas blancas y borde fino.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'mentorProfile',
      name: 'Quién te Guía',
      description: 'Presenta al mentor con claridad: quién es, qué ha logrado y por qué puede ayudar.',
      blueprint: 'Foto redondeada a un lado, biografía corta al otro. Insignias de autoridad.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'testimonials',
      name: 'Testimonios',
      description: 'Redacta 3-6 testimonios breves y concretos con resultado y nombre.',
      blueprint: 'Grilla 3 columnas de tarjetas suaves, cita corta y nombre abajo.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'bonuses',
      name: 'Extras',
      description: 'Describe recursos adicionales incluidos: plantillas, guías, acceso a comunidad.',
      blueprint: 'Tarjetas suaves con recurso a la izquierda y descripción corta a la derecha.',
      required: false, isRepeatable: true, contentType: 'mixed',
    },
    {
      id: 'guarantee',
      name: 'Garantía',
      description: 'Garantía simple y clara: plazo exacto y devolución total.',
      blueprint: 'Bloque centrado con sello simple, texto corto y directo.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'faqs',
      name: 'Preguntas Frecuentes',
      description: 'Responde objeciones con claridad: para quién es, tiempo, formato, forma de pago.',
      blueprint: 'Acordeones limpios en tarjetas blancas, sin complicación.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'countdownTimer',
      name: 'Oferta por Tiempo',
      description: 'Urgencia honesta: precio especial o cupos limitados.',
      blueprint: 'Barra simple con fondo accent claro, reloj discreto.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'footer',
      name: 'Pie de Página',
      description: 'Disclaimer corto, copyright y contacto.',
      blueprint: 'Texto small centrado, aviso legal en 1 línea.',
      required: false, isRepeatable: false, contentType: 'text',
    },
  ],
  defaultVisibility: {
    heroVideo: true,
    narrativeSections: true,
    benefits: true,
    syllabus: true,
    mentorProfile: true,
    testimonials: false,
    bonuses: false,
    guarantee: true,
    faqs: false,
    countdownTimer: false,
    footer: true,
  },
  colorProposals: modernCleanColorProposals,
  aiDirectives: 'Eres un redactor moderno y cercano. Tono claro, honesto y directo: cada frase debe ser entendible de inmediato. Beneficios concretos, sin exageraciones ni jerga.',
  aiWriterPersona: 'Copywriter moderno. Escribe claro y sin rodeos. El usuario entiende el valor en 5 segundos. Cercanía y claridad por encima de drama.',
};
