import { LandingStyle, StyleBrand, StyleTokens, TypographyVariant, ColorPalette } from './types';

const techB2bBaseTokens: StyleTokens = {
  componentRadius: '8px',
  componentBorder: '1px solid rgba(2,6,23,0.08)',
  componentShadow: '0 1px 3px rgba(2,6,23,0.08)',
  componentBg: '#FFFFFF',
  sectionPadding: '88px',
  contentGap: '22px',
  transitionDuration: '180ms',
  themeMode: 'light',
  extraTokens: {
    buttonStyle: 'filled',
    buttonRadius: '8px',
    ctaShadow: 'none',
    sectionBgAlternate: '#F0F4F8',
    containerMaxWidth: '1180px',
    headingWeight: '600',
    headingLetterSpacing: '-0.01em',
    gradientOverlay: 'linear-gradient(120deg, rgba(30,64,175,0.06), rgba(56,192,255,0.06))',
    overlayOpacity: '1',
    navbarHeight: '64px',
    countdownStyle: 'normal',
  },
};

const techB2bTypography: TypographyVariant[] = [
  { name: 'Técnico Limpio', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Inter', bodyFont: 'Inter' },
  { name: 'Sistema', headingScale: 1.15, bodyScale: 1.0, headingFont: 'IBM Plex Sans', bodyFont: 'IBM Plex Sans' },
  { name: 'Código', headingScale: 1.2, bodyScale: 1.0, headingFont: 'JetBrains Mono', bodyFont: 'Inter' },
  { name: 'Ingeniería', headingScale: 1.2, bodyScale: 1.05, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
  { name: 'Plataforma', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Public Sans', bodyFont: 'Inter' },
  { name: 'Blueprint', headingScale: 1.2, bodyScale: 1.0, headingFont: 'IBM Plex Mono', bodyFont: 'Inter' },
  { name: 'Modular', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Sora', bodyFont: 'Inter' },
  { name: 'Datos', headingScale: 1.1, bodyScale: 1.0, headingFont: 'Manrope', bodyFont: 'Inter' },
];

const techB2bColorProposals: ColorPalette[] = [
  { name: 'SaaS Azul', primary: '#1E40AF', secondary: '#F8FAFC', accent: '#F97316' },
  { name: 'Ventura Verde', primary: '#065F46', secondary: '#F0FDF4', accent: '#10B981' },
  { name: 'Estadística Índigo', primary: '#312E81', secondary: '#EEF2FF', accent: '#6366F1' },
  { name: 'Servidor Oscuro', primary: '#0B1220', secondary: '#F1F5F9', accent: '#38BDF8' },
  { name: 'Cerebro Púrpura', primary: '#4C1D95', secondary: '#FAF5FF', accent: '#8B5CF6' },
  { name: 'API Cian', primary: '#0E7490', secondary: '#ECFEFF', accent: '#06B6D4' },
  { name: 'Dashboard Grafito', primary: '#1F2937', secondary: '#F9FAFB', accent: '#F59E0B' },
  { name: 'Soporte Rojo', primary: '#991B1B', secondary: '#FEF2F2', accent: '#EF4444' },
];

const techB2bBrands: StyleBrand[] = [
  {
    name: 'Nube Empresarial',
    description: 'Azul SaaS con acento naranja: plataforma B2B para equipos.',
    tokens: {
      componentRadius: '8px',
      componentBorder: '1px solid rgba(30,64,175,0.15)',
      componentShadow: '0 2px 8px rgba(30,64,175,0.08)',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '22px',
      transitionDuration: '180ms',
      themeMode: 'light',
    },
    typography: { name: 'Técnico Limpio', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Inter', bodyFont: 'Inter' },
    palette: { name: 'SaaS Azul', primary: '#1E40AF', secondary: '#F8FAFC', accent: '#F97316' },
  },
  {
    name: 'Motor de Datos',
    description: 'Índigo analítico: cifras, dashboards y resultados medibles.',
    tokens: {
      componentRadius: '8px',
      componentBorder: '1px solid rgba(49,46,129,0.15)',
      componentShadow: '0 2px 8px rgba(49,46,129,0.08)',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '22px',
      transitionDuration: '180ms',
      themeMode: 'light',
    },
    typography: { name: 'Datos', headingScale: 1.1, bodyScale: 1.0, headingFont: 'Manrope', bodyFont: 'Inter' },
    palette: { name: 'Estadística Índigo', primary: '#312E81', secondary: '#EEF2FF', accent: '#6366F1' },
  },
  {
    name: 'Backend Negro',
    description: 'Servidor oscuro y cian: infraestructura técnica y devtools.',
    tokens: {
      componentRadius: '6px',
      componentBorder: '1px solid rgba(148,163,184,0.2)',
      componentShadow: '0 2px 8px rgba(11,18,32,0.2)',
      componentBg: 'rgba(255,255,255,0.04)',
      sectionPadding: '96px',
      contentGap: '24px',
      transitionDuration: '200ms',
      themeMode: 'dark',
    },
    typography: { name: 'Código', headingScale: 1.2, bodyScale: 1.0, headingFont: 'JetBrains Mono', bodyFont: 'Inter' },
    palette: { name: 'Servidor Oscuro', primary: '#0B1220', secondary: '#F1F5F9', accent: '#38BDF8' },
  },
  {
    name: 'DevTools',
    description: 'API cian: integraciones, documentación y desarrolladores.',
    tokens: {
      componentRadius: '8px',
      componentBorder: '1px solid rgba(14,116,144,0.2)',
      componentShadow: '0 2px 8px rgba(14,116,144,0.08)',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '22px',
      transitionDuration: '180ms',
      themeMode: 'light',
    },
    typography: { name: 'Sistema', headingScale: 1.15, bodyScale: 1.0, headingFont: 'IBM Plex Sans', bodyFont: 'IBM Plex Sans' },
    palette: { name: 'API Cian', primary: '#0E7490', secondary: '#ECFEFF', accent: '#06B6D4' },
  },
  {
    name: 'Analítica',
    description: 'Grafito y ámbar: reporting, dashboards y gestión.',
    tokens: {
      componentRadius: '8px',
      componentBorder: '1px solid rgba(31,41,55,0.12)',
      componentShadow: '0 2px 8px rgba(31,41,55,0.06)',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '22px',
      transitionDuration: '180ms',
      themeMode: 'light',
    },
    typography: { name: 'Modular', headingScale: 1.15, bodyScale: 1.0, headingFont: 'Sora', bodyFont: 'Inter' },
    palette: { name: 'Dashboard Grafito', primary: '#1F2937', secondary: '#F9FAFB', accent: '#F59E0B' },
  },
  {
    name: 'Plataforma Escalable',
    description: 'Verde venture: growth, escala y métricas de producto.',
    tokens: {
      componentRadius: '10px',
      componentBorder: '1px solid rgba(6,95,70,0.15)',
      componentShadow: '0 2px 10px rgba(6,95,70,0.08)',
      componentBg: '#FFFFFF',
      sectionPadding: '88px',
      contentGap: '24px',
      transitionDuration: '200ms',
      themeMode: 'light',
    },
    typography: { name: 'Ingeniería', headingScale: 1.2, bodyScale: 1.05, headingFont: 'Space Grotesk', bodyFont: 'Inter' },
    palette: { name: 'Ventura Verde', primary: '#065F46', secondary: '#F0FDF4', accent: '#10B981' },
  },
];

export const techB2bStyle: LandingStyle = {
  id: 'tech-b2b',
  name: 'Tech B2B',
  description: 'B2B SaaS técnico: cifras, screenshots y lenguaje de producto para decisiones racionales.',
  thumbnail: '/styles/tech-b2b-thumb.svg',
  group: 'corporate',
  allowedSubscriptions: ['free', 'pro', 'premium'],
  layout: 'grid',
  tokens: techB2bBaseTokens,
  typography: techB2bTypography,
  brands: techB2bBrands,
  availableSections: [
    {
      id: 'heroVideo',
      name: 'Hero de Producto',
      description: 'Redacta el hero B2B: qué resuelve el producto/curso para un equipo o empresa, con métrica o caso concreto. CTA claro de demo o suscripción.',
      blueprint: 'Split: izquierda copy (eyebrow técnico en mono, H1, subhead con métrica, CTA), derecha screenshot de dashboard o producto. Fondo claro, bordes finos.',
      required: true, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'narrativeSections',
      name: 'Secciones de Argumento',
      description: 'Argumenta con datos: el costo del problema, la eficiencia de la solución y el retorno medible. Viñetas con cifras.',
      blueprint: 'Bloques alternados con screenshot o tabla de datos. Títulos en primario, cifras destacadas en mono.',
      required: true, isRepeatable: true, contentType: 'mixed',
    },
    {
      id: 'benefits',
      name: 'Capacidades',
      description: 'Enumera capacidades concretas del programa/producto: automatización, integraciones, métricas. Concretas y verificables.',
      blueprint: 'Grilla de tarjetas blancas con ícono, título y 2-3 líneas. Borde fino y radius de 8px.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'syllabus',
      name: 'Ruta Técnica',
      description: 'Describe la ruta de aprendizaje como módulos técnicos con entregable al final de cada uno (dashboard, script, deploy).',
      blueprint: 'Lista numerada 2 columnas. Número en mono, título en bold, descripción breve. Separadores finos.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'mentorProfile',
      name: 'Líder Técnico',
      description: 'Presenta al instructor con credibilidad técnica: stack, experiencia, resultados de equipos dirigidos.',
      blueprint: 'Split: foto profesional, biografía con insignias técnicas, métricas de impacto.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'testimonials',
      name: 'Casos de Clientes',
      description: 'Redacta 3-6 casos con resultado medible (tiempo ahorrado, ingresos, eficiencia) y nombre/rol real.',
      blueprint: 'Tarjetas con métrica destacada en mono arriba, cita corta, nombre y rol abajo.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'bonuses',
      name: 'Recursos Incluidos',
      description: 'Describe recursos técnicos incluidos (plantillas, código, acceso a herramientas) con valor.',
      blueprint: 'Tarjetas apiladas con recurso a la izquierda y descripción a la derecha.',
      required: false, isRepeatable: true, contentType: 'mixed',
    },
    {
      id: 'guarantee',
      name: 'Garantía',
      description: 'Redacta la garantía en tono técnico y directo: plazo exacto y devolución total.',
      blueprint: 'Bloque formal con borde fino, ícono de sello, texto corto y claro.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'faqs',
      name: 'Preguntas Técnicas',
      description: 'Responde objeciones técnicas y de compra: integraciones, requisitos, soporte, licencias.',
      blueprint: 'Acordeones con separadores finos. Respuesta corta y concreta.',
      required: false, isRepeatable: false, contentType: 'text',
    },
    {
      id: 'countdownTimer',
      name: 'Oferta de Equipo',
      description: 'Genera urgencia racional: descuento por tiempo o cupos de onboarding.',
      blueprint: 'Barra con fondo accent, reloj de dígitos, texto sobrio.',
      required: false, isRepeatable: false, contentType: 'mixed',
    },
    {
      id: 'footer',
      name: 'Pie de Página',
      description: 'Disclaimer, copyright y datos de contacto.',
      blueprint: 'Texto centrado small, aviso legal en 1 línea.',
      required: false, isRepeatable: false, contentType: 'text',
    },
  ],
  defaultVisibility: {
    heroVideo: true,
    narrativeSections: true,
    benefits: true,
    syllabus: true,
    mentorProfile: false,
    testimonials: true,
    bonuses: false,
    guarantee: true,
    faqs: true,
    countdownTimer: false,
    footer: true,
  },
  colorProposals: techB2bColorProposals,
  aiDirectives: 'Eres un redactor técnico B2B. Tono racional y concreto: métricas verificables, lenguaje de producto, sin superlativos vacíos. Cada beneficio debe traducirse en un dato o una capacidad medible.',
  aiWriterPersona: 'Copywriter de tecnología B2B. Escribe para decisiones racionales: claro, técnico pero accesible, con cifras y casos. Sin ruido ni exageraciones.',
};
