'use client';

import { useAuth } from '@/components/auth-context';
import { DashboardLayout } from '@/components/dashboard/dashboard-layout';
import { collection, query, where, getDocs, orderBy } from 'firebase/firestore';
import { useFirestore } from '@/firebase';
import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ResponsiveTable } from '@/components/ui/responsive-table';
import { 
  Users, 
  Target, 
  Percent, 
  Link as LinkIcon, 
  Copy,
  CheckCircle2,
  Clock,
  Loader2,
  ExternalLink
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';

export default function ReferidosDashboard() {
  const { profile, isLoading: isAuthLoading } = useAuth();
  const db = useFirestore();
  const { toast } = useToast();

  const [landings, setLandings] = useState<any[]>([]);
  const [leads, setLeads] = useState<any[]>([]);
  const [loadingData, setLoadingData] = useState(true);

  useEffect(() => {
    if (!profile?.uid) return;

    const fetchData = async () => {
      try {
        setLoadingData(true);
        
        // 1. Fetch landings assigned to this referrer
        const qLandings = query(
          collection(db, 'salesPages'),
          where('referidoId', '==', profile.uid)
        );
        const landingsSnap = await getDocs(qLandings);
        const landingsData = landingsSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        setLandings(landingsData);

        // 2. Fetch leads generated by this referrer
        const qLeads = query(
          collection(db, 'leads'),
          where('referidoId', '==', profile.uid)
        );
        const leadsSnap = await getDocs(qLeads);
        const leadsData = leadsSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        
        // Sort leads by date descending (client side since we didn't index)
        leadsData.sort((a: any, b: any) => {
          const tA = a.createdAt?.seconds || 0;
          const tB = b.createdAt?.seconds || 0;
          return tB - tA;
        });

        setLeads(leadsData);
      } catch (err) {
        console.error("Error fetching referidos data:", err);
      } finally {
        setLoadingData(false);
      }
    };

    fetchData();
  }, [db, profile?.uid]);

  const handleCopyLink = (landingId: string) => {
    if (!profile?.uid) return;
    const url = `${window.location.origin}/v/${landingId}?ref=${profile.uid}`;
    navigator.clipboard.writeText(url);
    toast({
      title: "Enlace Copiado",
      description: "El enlace de referido ha sido copiado al portapapeles.",
    });
  };

  if (isAuthLoading || loadingData) {
    return (
      <DashboardLayout>
        <div className="flex h-[80vh] items-center justify-center">
          <Loader2 className="h-10 w-10 animate-spin text-accent/20" />
        </div>
      </DashboardLayout>
    );
  }

  // Calculate Metrics
  const totalLeads = leads.length;
  const convertedLeads = leads.filter(l => l.status === 'converted').length;
  const conversionRate = totalLeads > 0 ? Math.round((convertedLeads / totalLeads) * 100) : 0;

  const leadTableColumns = [
    {
      key: 'estudiante',
      header: 'Estudiante',
      hideOnMobile: true,
      cell: (lead: any) => (
        <>
          <div className="font-bold text-foreground">{lead.studentName}</div>
          <div className="text-xs text-muted-foreground">{lead.studentEmail}</div>
        </>
      ),
    },
    {
      key: 'fecha',
      header: 'Fecha',
      cell: (lead: any) => {
        const date = lead.createdAt?.seconds
          ? format(new Date(lead.createdAt.seconds * 1000), "dd MMM yyyy, HH:mm", { locale: es })
          : 'Reciente';
        return (
          <span className="text-muted-foreground text-xs font-medium">{date}</span>
        );
      },
    },
    {
      key: 'estado',
      header: 'Estado',
      hideOnMobile: true,
      cell: (lead: any) => (
        lead.status === 'converted' ? (
          <div className="inline-flex items-center gap-1.5 bg-success/10 text-success px-2.5 py-1 rounded-md text-[11px] font-bold">
            <CheckCircle2 className="h-3.5 w-3.5" /> Pago Confirmado
          </div>
        ) : (
          <div className="inline-flex items-center gap-1.5 bg-warn/10 text-warn px-2.5 py-1 rounded-md text-[11px] font-bold">
            <Clock className="h-3.5 w-3.5" /> Pendiente de Pago
          </div>
        )
      ),
    },
  ];

  return (
    <DashboardLayout>
      <div className="max-w-6xl mx-auto space-y-10 md:space-y-16 animate-in fade-in slide-in-from-bottom-4 duration-700 py-6">
        
        {/* Header */}
        <div>
          <h1 className="text-2xl md:text-4xl font-black text-foreground tracking-tight flex items-center gap-3">
            Panel de Referidos
            <Badge className="bg-accent/10 text-accent border-none rounded-full px-3 py-1">Embajador</Badge>
          </h1>
          <p className="text-sm md:text-base text-muted-foreground mt-2 font-medium">
            Gestiona tus enlaces asignados y monitorea en tiempo real los leads generados y tus conversiones.
          </p>
        </div>

        {/* Metrics */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="border-none rounded-2xl bg-gradient-to-br from-primary to-primary text-white overflow-hidden relative">
            <Users className="absolute -right-4 -bottom-4 h-32 w-32 opacity-10" />
            <CardContent className="p-8">
              <p className="text-primary/15 font-bold uppercase text-[10px] tracking-widest mb-2">Total Leads</p>
              <p className="text-5xl font-black">{totalLeads}</p>
            </CardContent>
          </Card>
          
          <Card className="border-none rounded-2xl bg-gradient-to-br from-success to-teal-600 text-white overflow-hidden relative">
            <Target className="absolute -right-4 -bottom-4 h-32 w-32 opacity-10" />
            <CardContent className="p-8">
              <p className="text-success/15 font-bold uppercase text-[10px] tracking-widest mb-2">Ventas Exitosas</p>
              <p className="text-5xl font-black">{convertedLeads}</p>
            </CardContent>
          </Card>

          <Card className="border-none rounded-2xl bg-foreground text-white overflow-hidden relative">
            <Percent className="absolute -right-4 -bottom-4 h-32 w-32 opacity-5" />
            <CardContent className="p-8">
              <p className="text-muted-foreground font-bold uppercase text-[10px] tracking-widest mb-2">Conversión</p>
              <p className="text-5xl font-black text-accent">{conversionRate}%</p>
            </CardContent>
          </Card>
        </div>

        {/* Landings Asignadas */}
        <div className="space-y-6">
          <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
            <LinkIcon className="h-5 w-5 text-accent" />
            Mis Enlaces (Landings Asignadas)
          </h2>
          
          {landings.length === 0 ? (
            <div className="bg-muted rounded-2xl p-10 border border-dashed border-border text-center">
              <p className="text-muted-foreground">No tienes landings asignadas actualmente.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {landings.map(landing => {
                const isActive = landing.activeUntil 
                  ? new Date(landing.activeUntil.seconds * 1000) > new Date()
                  : true; // If no activeUntil, assume active
                  
                return (
                  <Card key={landing.id} className="border-none shadow-lg rounded-2xl overflow-hidden transition-all">
                    <CardHeader className="bg-muted pb-4 border-b border-muted">
                      <div className="flex justify-between items-start">
                        <div>
                          <CardTitle className="text-lg text-foreground line-clamp-1">{landing.title}</CardTitle>
                          <CardDescription className="text-xs mt-1">
                            {landing.courseName || 'Programa General'}
                          </CardDescription>
                        </div>
                        <Badge className={isActive ? 'bg-success' : 'bg-danger'}>
                          {isActive ? 'Activa' : 'Expirada'}
                        </Badge>
                      </div>
                    </CardHeader>
                    <CardContent className="p-6">
                      <div className="flex flex-col gap-4">
                        <div className="bg-muted/50 p-3 rounded-xl border border-border/60 font-mono text-xs text-muted-foreground truncate">
                          {`${window.location.origin}/v/${landing.id}?ref=${profile?.uid}`}
                        </div>
                        <div className="flex items-center gap-3">
                          <Button 
                            onClick={() => handleCopyLink(landing.id)}
                            className="flex-1 bg-accent hover:bg-accent/90 text-white rounded-xl shadow-lg gap-2"
                          >
                            <Copy className="h-4 w-4" /> Copiar Enlace
                          </Button>
                          <Button 
                            variant="outline" 
                            size="icon"
                            className="rounded-xl shrink-0"
                            onClick={() => window.open(`/v/${landing.id}?ref=${profile?.uid}`, '_blank')}
                          >
                            <ExternalLink className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </div>

        {/* Historial de Leads */}
        <div className="space-y-6">
          <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
            <Users className="h-5 w-5 text-accent" />
            Historial de Leads
          </h2>
          
          <Card className="rounded-lg overflow-hidden">
            <ResponsiveTable
              columns={leadTableColumns}
              data={leads}
              keyExtractor={(lead) => lead.id}
              emptyState={
                <div className="px-6 py-10 text-center text-muted-foreground italic">
                  Aún no tienes leads registrados. Comparte tus enlaces para comenzar.
                </div>
              }
              mobileCardHeader={(lead: any) => {
                const date = lead.createdAt?.seconds
                  ? format(new Date(lead.createdAt.seconds * 1000), "dd MMM yyyy, HH:mm", { locale: es })
                  : 'Reciente';
                return (
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <p className="font-bold text-sm text-foreground leading-tight">{lead.studentName}</p>
                      <p className="text-xs text-muted-foreground mt-0.5">{lead.studentEmail}</p>
                    </div>
                    {lead.status === 'converted' ? (
                      <div className="inline-flex items-center gap-1.5 bg-success/10 text-success px-2.5 py-1 rounded-md text-[11px] font-bold shrink-0">
                        <CheckCircle2 className="h-3.5 w-3.5" /> Pago Confirmado
                      </div>
                    ) : (
                      <div className="inline-flex items-center gap-1.5 bg-warn/10 text-warn px-2.5 py-1 rounded-md text-[11px] font-bold shrink-0">
                        <Clock className="h-3.5 w-3.5" /> Pendiente de Pago
                      </div>
                    )}
                  </div>
                );
              }}
            />
          </Card>
        </div>

      </div>
    </DashboardLayout>
  );
}
