'use client';

import { useAuth } from '@/components/auth-context';
import { DashboardLayout } from '@/components/dashboard/dashboard-layout';
import { collection, query, where, getDocs, orderBy } from 'firebase/firestore';
import { useFirestore } from '@/firebase';
import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Users, 
  Target, 
  Percent, 
  Link as LinkIcon, 
  Copy,
  CheckCircle2,
  Clock,
  Loader2,
  ExternalLink
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';

export default function ReferidosDashboard() {
  const { profile, isLoading: isAuthLoading } = useAuth();
  const db = useFirestore();
  const { toast } = useToast();

  const [landings, setLandings] = useState<any[]>([]);
  const [leads, setLeads] = useState<any[]>([]);
  const [loadingData, setLoadingData] = useState(true);

  useEffect(() => {
    if (!profile?.uid) return;

    const fetchData = async () => {
      try {
        setLoadingData(true);
        
        // 1. Fetch landings assigned to this referrer
        const qLandings = query(
          collection(db, 'salesPages'),
          where('referidoId', '==', profile.uid)
        );
        const landingsSnap = await getDocs(qLandings);
        const landingsData = landingsSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        setLandings(landingsData);

        // 2. Fetch leads generated by this referrer
        const qLeads = query(
          collection(db, 'leads'),
          where('referidoId', '==', profile.uid)
        );
        const leadsSnap = await getDocs(qLeads);
        const leadsData = leadsSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        
        // Sort leads by date descending (client side since we didn't index)
        leadsData.sort((a: any, b: any) => {
          const tA = a.createdAt?.seconds || 0;
          const tB = b.createdAt?.seconds || 0;
          return tB - tA;
        });

        setLeads(leadsData);
      } catch (err) {
        console.error("Error fetching referidos data:", err);
      } finally {
        setLoadingData(false);
      }
    };

    fetchData();
  }, [db, profile?.uid]);

  const handleCopyLink = (landingId: string) => {
    if (!profile?.uid) return;
    const url = `${window.location.origin}/v/${landingId}?ref=${profile.uid}`;
    navigator.clipboard.writeText(url);
    toast({
      title: "Enlace Copiado",
      description: "El enlace de referido ha sido copiado al portapapeles.",
    });
  };

  if (isAuthLoading || loadingData) {
    return (
      <DashboardLayout>
        <div className="flex h-[80vh] items-center justify-center">
          <Loader2 className="h-10 w-10 animate-spin text-accent/20" />
        </div>
      </DashboardLayout>
    );
  }

  // Calculate Metrics
  const totalLeads = leads.length;
  const convertedLeads = leads.filter(l => l.status === 'converted').length;
  const conversionRate = totalLeads > 0 ? Math.round((convertedLeads / totalLeads) * 100) : 0;

  return (
    <DashboardLayout>
      <div className="max-w-6xl mx-auto space-y-10 md:space-y-16 animate-in fade-in slide-in-from-bottom-4 duration-700 py-6">
        
        {/* Header */}
        <div>
          <h1 className="text-2xl md:text-4xl font-black text-slate-900 tracking-tight flex items-center gap-3">
            Panel de Referidos
            <Badge className="bg-accent/10 text-accent border-none rounded-full px-3 py-1">Embajador</Badge>
          </h1>
          <p className="text-sm md:text-base text-slate-500 mt-2 font-medium">
            Gestiona tus enlaces asignados y monitorea en tiempo real los leads generados y tus conversiones.
          </p>
        </div>

        {/* Metrics */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="border-none rounded-2xl bg-gradient-to-br from-indigo-500 to-purple-600 text-white overflow-hidden relative">
            <Users className="absolute -right-4 -bottom-4 h-32 w-32 opacity-10" />
            <CardContent className="p-8">
              <p className="text-indigo-100 font-bold uppercase text-[10px] tracking-widest mb-2">Total Leads</p>
              <p className="text-5xl font-black">{totalLeads}</p>
            </CardContent>
          </Card>
          
          <Card className="border-none rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white overflow-hidden relative">
            <Target className="absolute -right-4 -bottom-4 h-32 w-32 opacity-10" />
            <CardContent className="p-8">
              <p className="text-emerald-100 font-bold uppercase text-[10px] tracking-widest mb-2">Ventas Exitosas</p>
              <p className="text-5xl font-black">{convertedLeads}</p>
            </CardContent>
          </Card>

          <Card className="border-none rounded-2xl bg-slate-900 text-white overflow-hidden relative">
            <Percent className="absolute -right-4 -bottom-4 h-32 w-32 opacity-5" />
            <CardContent className="p-8">
              <p className="text-slate-400 font-bold uppercase text-[10px] tracking-widest mb-2">Conversión</p>
              <p className="text-5xl font-black text-accent">{conversionRate}%</p>
            </CardContent>
          </Card>
        </div>

        {/* Landings Asignadas */}
        <div className="space-y-6">
          <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <LinkIcon className="h-5 w-5 text-accent" />
            Mis Enlaces (Landings Asignadas)
          </h2>
          
          {landings.length === 0 ? (
            <div className="bg-slate-50 rounded-2xl p-10 border border-dashed border-slate-200 text-center">
              <p className="text-slate-500">No tienes landings asignadas actualmente.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {landings.map(landing => {
                const isActive = landing.activeUntil 
                  ? new Date(landing.activeUntil.seconds * 1000) > new Date()
                  : true; // If no activeUntil, assume active
                  
                return (
                  <Card key={landing.id} className="border-none shadow-lg rounded-2xl overflow-hidden transition-all">
                    <CardHeader className="bg-slate-50 pb-4 border-b border-slate-100">
                      <div className="flex justify-between items-start">
                        <div>
                          <CardTitle className="text-lg text-slate-800 line-clamp-1">{landing.title}</CardTitle>
                          <CardDescription className="text-xs mt-1">
                            {landing.courseName || 'Programa General'}
                          </CardDescription>
                        </div>
                        <Badge className={isActive ? 'bg-emerald-500' : 'bg-red-500'}>
                          {isActive ? 'Activa' : 'Expirada'}
                        </Badge>
                      </div>
                    </CardHeader>
                    <CardContent className="p-6">
                      <div className="flex flex-col gap-4">
                        <div className="bg-slate-100/50 p-3 rounded-xl border border-slate-200/60 font-mono text-xs text-slate-600 truncate">
                          {`${window.location.origin}/v/${landing.id}?ref=${profile?.uid}`}
                        </div>
                        <div className="flex items-center gap-3">
                          <Button 
                            onClick={() => handleCopyLink(landing.id)}
                            className="flex-1 bg-accent hover:bg-accent/90 text-white rounded-xl shadow-lg gap-2"
                          >
                            <Copy className="h-4 w-4" /> Copiar Enlace
                          </Button>
                          <Button 
                            variant="outline" 
                            size="icon"
                            className="rounded-xl shrink-0"
                            onClick={() => window.open(`/v/${landing.id}?ref=${profile?.uid}`, '_blank')}
                          >
                            <ExternalLink className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </div>

        {/* Historial de Leads */}
        <div className="space-y-6">
          <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <Users className="h-5 w-5 text-accent" />
            Historial de Leads
          </h2>
          
          <Card className="rounded-lg overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="text-[10px] text-slate-500 uppercase bg-slate-50/80 font-black tracking-widest border-b border-slate-100">
                  <tr>
                    <th className="px-6 py-4">Estudiante</th>
                    <th className="px-6 py-4">Fecha</th>
                    <th className="px-6 py-4">Estado</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {leads.length === 0 ? (
                    <tr>
                      <td colSpan={3} className="px-6 py-10 text-center text-slate-500 italic">
                        Aún no tienes leads registrados. Comparte tus enlaces para comenzar.
                      </td>
                    </tr>
                  ) : (
                    leads.map(lead => {
                      const date = lead.createdAt?.seconds 
                        ? format(new Date(lead.createdAt.seconds * 1000), "dd MMM yyyy, HH:mm", { locale: es })
                        : 'Reciente';
                      
                      return (
                        <tr key={lead.id} className="hover:bg-slate-50/50 transition-colors">
                          <td className="px-6 py-4">
                            <div className="font-bold text-slate-800">{lead.studentName}</div>
                            <div className="text-xs text-slate-500">{lead.studentEmail}</div>
                          </td>
                          <td className="px-6 py-4 text-slate-500 text-xs font-medium">
                            {date}
                          </td>
                          <td className="px-6 py-4">
                            {lead.status === 'converted' ? (
                              <div className="inline-flex items-center gap-1.5 bg-emerald-50 text-emerald-600 px-2.5 py-1 rounded-md text-[11px] font-bold">
                                <CheckCircle2 className="h-3.5 w-3.5" /> Pago Confirmado
                              </div>
                            ) : (
                              <div className="inline-flex items-center gap-1.5 bg-amber-50 text-amber-600 px-2.5 py-1 rounded-md text-[11px] font-bold">
                                <Clock className="h-3.5 w-3.5" /> Pendiente de Pago
                              </div>
                            )}
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>
          </Card>
        </div>

      </div>
    </DashboardLayout>
  );
}
